#!/usr/bin/env zsh

# Description: This script executes a bunch of commands I run frequently to
# keep things up-to-date etc.
#
# Usage: maintenance
#
# Written by Göran Gustafsson (gustafsson.g at gmail.com).
# License: BSD 3-Clause.

sudo apt update
sudo apt full-upgrade
sudo apt autoremove

for directory in ~/Projects/*; do
  if [[ -d $directory ]]; then
    print -P "\n%B%F{cyan}Updating repo: ${directory/${HOME}/~}%f%b"
    git -C $directory pull
  fi
done

echo
fetch-vim
