#!/usr/bin/env zsh

# Description: Executes a bunch of commands I run frequently to keep things
# up-to-date etc.
#
# Usage: maint
#
# Creator: Göran Gustafsson (gustafsson.g at gmail.com)
# License: BSD 3-Clause

sudo apt update
sudo apt full-upgrade
sudo apt autoremove

for directory in ~/Projects/*(N); do
  if git -C $directory rev-parse --is-inside-work-tree &> /dev/null; then
    print -P "\n%F{cyan}Updating repo: ${directory:t}%f"
    git -C $directory pull
  fi
done

echo
maint-vim
