#!/usr/bin/env zsh

# Description: This script executes a bunch of commands I run frequently to
# keep things up-to-date etc.
#
# Usage: maint
#
# Creator: Göran Gustafsson (gustafsson.g at gmail.com)
# License: BSD 3-Clause

sudo apt update
sudo apt full-upgrade
sudo apt autoremove

for directory in ~/Projects/*(N); do
  if [[ -d ${directory}/.git ]]; then
    print -P "\n%F{cyan}Updating repo: ${directory/${HOME}/~}%f"
    git -C $directory pull
  fi
done

echo; maint-vim
