#!/bin/bash

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

# Description: This script configures a Ubuntu system the way i like.

# Usage: setup_ubuntu

rm ~/examples.desktop

sudo apt install \
  curl \
  flac \
  git \
  links \
  nmap \
  openssh-server \
  tmux \
  tree \
  vim-nox \
  weechat \
  zsh

sudo chsh -s /bin/zsh $USER

mkdir ~/Projects
git clone https://github.com/ggustafsson/Dot-Files.git ~/Projects/Dot\ Files

~/Projects/Dot\ Files/Scripts/setup_dotfiles
