#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

# Description: This script automates the installation of VMware Tools.

# Usage: setup_vmware

if [[ -d /media/gleg/VMware\ Tools ]]; then
  tar -xf /media/gleg/VMware\ Tools/VMwareTools-*.tar.gz -C ~/ && \
    sudo ~/vmware-tools-distrib/vmware-install.pl -d && \
    rm -rf ~/vmware-tools-distrib
else
  echo "VMware Tools directory not found! Exiting..."
  exit 1
fi
