#!/bin/bash

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

# Description: This script configures specific things for my media center.

# Usage: setup_ubuntu_tv

sudo apt-get install \
  default-jre \
  nagios3 \
  openssh-server \
  sshguard \
  xbmc
