#!/bin/bash

# Description: This script configures specific things for my virtual machines.
#
# Usage: setup_ubuntu_vm
#
# Written by Göran Gustafsson (gustafsson.g at gmail.com).
# License: BSD 3-Clause.

sudo apt install \
  apache2 \
  bind9 \
  dia \
  gnupg2 \
  gnuplot \
  golang \
  gparted \
  hping3 \
  ncftp \
  netperf \
  nfs-kernel-server \
  nginx \
  open-vm-tools \
  open-vm-tools-desktop \
  php5 \
  r-base \
  samba \
  shntool \
  sslstrip \
  tftp \
  tftpd \
  tshark \
  wireshark

sudo dpkg-reconfigure wireshark-common
sudo usermod -a -G dialout,wireshark $USER

sudo rm \
  /etc/rc*.d/*apache2 \
  /etc/rc*.d/*bind9 \
  /etc/rc*.d/*netperf \
  /etc/rc*.d/*nfs-kernel-server \
  /etc/rc*.d/*nginx

echo manual | sudo tee /etc/init/smbd.override
echo manual | sudo tee /etc/init/ssh.override
