#!/bin/bash

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

# Description: This script configures specific things for my media center.

# Usage: setup_ubuntu_tv

sudo add-apt-repository ppa:team-xbmc/ppa
sudo apt-get update

sudo apt install \
  sshguard \
  weechat \
  xbmc
