#!/bin/bash

# Description: This script configures specific things for my media center.

# Usage: setup_ubuntu_tv

# Written by Göran Gustafsson (gustafsson.g at gmail.com).
# License: BSD 3-Clause.

sudo add-apt-repository ppa:team-xbmc/ppa
sudo apt-get update

sudo apt install \
  abcde \
  kodi \
  sshguard
