#!/bin/bash

# Description: This script configures specific things for my media center.
#
# Usage: setup-ubuntu-tv
#
# Written by Göran Gustafsson (gustafsson.g at gmail.com).
# License: BSD 3-Clause.

sudo apt install -y \
  abcde \
  sshguard

echo
git clone --depth=1 https://github.com/RetroPie/RetroPie-Setup.git
cd RetroPie-Setup
sudo ./retropie_setup.sh
