#!/bin/bash

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

# Description: This script configures a Ubuntu system the way i like.

# Usage: setup_ubuntu

if [[ ! -f ~/.ssh/id_rsa ]]; then
  echo "Install the SSH key first! Exiting..."
  return 1
fi

rm ~/examples.desktop

sudo apt-get install \
  git \
  tmux \
  tree \
  vim-nox \
  zsh

sudo chsh -s /bin/zsh $USER

mkdir ~/Projects
git clone git@github.com:ggustafsson/Dot-Files.git ~/Projects/Dot\ Files

~/Projects/Dot\ Files/Scripts/setup_dotfiles
