#!/bin/bash

# Description: Configures a Ubuntu system the way I like. This will be ported
# over to Ansible Playbook any year now.
#
# Usage: setup-ubuntu
#
# Creator: Göran Gustafsson (gustafsson.g at gmail.com)
# License: BSD 3-Clause

mkdir -m 700 ~/.ssh
mkdir -p ~/.vim/backups
mkdir -p ~/.vim/pack/ggustafsson/start
mkdir -p ~/.vim/pack/others/start
mkdir -p ~/.vim/undos
mkdir ~/Projects


sudo apt install -y \
  ansible \
  ansible-lint \
  dnsutils \
  flac \
  flake8 \
  golang \
  html2text \
  links \
  nmap \
  pylint3 \
  ruby \
  shellcheck \
  tidy \
  tree \
  yamllint \
  zsh

sudo chsh -s /bin/zsh $USER


echo
git clone https://github.com/ggustafsson/Dot-Files.git ~/Projects/Dot-Files
git clone https://github.com/ggustafsson/Static-Color-Scheme.git ~/Projects/Static-Color-Scheme

ln -s ~/Projects/Dot-Files/Scripts ~/
ln -s ~/Projects/Dot-Files/gitconfig ~/.gitconfig
ln -s ~/Projects/Dot-Files/gitignore_global ~/.gitignore_global
ln -s ~/Projects/Dot-Files/ssh_config ~/.ssh/config
ln -s ~/Projects/Dot-Files/vim/after ~/.vim/after
ln -s ~/Projects/Dot-Files/vim/templates ~/.vim/templates
ln -s ~/Projects/Dot-Files/vimrc ~/.vimrc
ln -s ~/Projects/Dot-Files/zshenv ~/.zshenv
ln -s ~/Projects/Dot-Files/zshrc ~/.zshrc
ln -s ~/Projects/Static-Color-Scheme ~/.vim/pack/ggustafsson/start/Static-Color-Scheme

sudo cp ~/Projects/Dot-Files/motd /etc/motd


echo
~/Scripts/maint-vim
