#!/bin/bash

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

# Description: This script configures a CentOS system the way i like.

# Usage: setup_centos

su -c "usermod -a -G wheel $USER && visudo"

sudo yum install \
  git \
  nmap \
  vim \
  zsh

sudo chsh -s /bin/zsh $USER

mkdir ~/Projects
git clone git://github.com/ggustafsson/Dot-Files.git ~/Projects/Dot\ Files

~/Projects/Dot\ Files/Scripts/setup_dotfiles
