#!/bin/bash

# Description: Configures misc things specific for my media center. This will
# be ported over to Ansible Playbook any year now.
#
# Usage: setup-ubuntu-tv
#
# Creator: Göran Gustafsson (gustafsson.g at gmail.com)
# License: BSD 3-Clause

sudo add-apt-repository ppa:team-xbmc/ppa
sudo apt update

sudo apt install -y \
  abcde \
  kodi \
  sshguard
