#!/bin/bash

# Description: This script configures specific things for my virtual machines.
#
# Usage: setup-ubuntu-vm
#
# Written by Göran Gustafsson (gustafsson.g at gmail.com).
# License: BSD 3-Clause.

sudo apt install -y \
  apache2 \
  bind9 \
  cntlm \
  cuetools \
  dia \
  gnuplot \
  gparted \
  hping3 \
  ncftp \
  netperf \
  nfs-kernel-server \
  nginx-full \
  open-vm-tools \
  open-vm-tools-desktop \
  php \
  r-base \
  samba \
  shntool \
  sslstrip \
  tftp \
  tftpd \
  tshark \
  wireshark

sudo usermod -a -G dialout,wireshark $USER

echo
services="apache2 bind9 cntlm netperf nfs-kernel-server nginx smbd ssh"
sudo systemctl disable $services
sudo systemctl stop $services

echo
mkdir -p ~/.fonts/truetype/Inconsolata
cp ~/Projects/Dot\ Files/Inconsolata.ttf ~/.fonts/truetype/Inconsolata/
fc-cache -f -v
