#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

# Description: This script automates the installation of VMware Tools.

# Usage: setup_vmware

vmware_path=/media/gleg/VMware\ Tools
output_path=~/vmware-tools-distrib

if [[ -d $vmware_path ]]; then
  tar -xf $vmware_path/VMwareTools-*.tar.gz -C ~/ && \
    sudo $output_path/vmware-install.pl -d && \
    rm -rf $output_path

  echo -n "Finished and ready to reboot? [y/n] "
  read answer

  if [[ $answer == (y|yes) ]]; then
    sudo reboot
  fi
else
  echo "VMware Tools directory not found! Exiting..."
  exit 1
fi
