#!/bin/bash

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

# Description: This script configures specific things for my media
# center/server. I use this after i got a basic configuration up and running.

# Usage: ubuntusetup-tv

sudo apt-get install \
  openssh-server \
  sshguard \
  transmission \
  xbmc \
  youtube-dl
