#!/bin/bash

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

# Description: This script configures a Ubuntu system the way i like.

# Usage: ubunutusetup

rm ~/examples.desktop

sudo apt-get install \
  cowsay \
  dsniff \
  ettercap-graphical \
  ffmpeg \
  figlet \
  flac \
  git \
  gparted \
  hping3 \
  html2text \
  imagemagick \
  irssi \
  kismet \
  lame \
  links \
  ncftp \
  netperf \
  nmap \
  openssh-server \
  php5 \
  ruby \
  sshguard \
  tmux \
  transmission \
  tree \
  tshark \
  vim-nox \
  vorbis-tools \
  wireshark \
  xbmc \
  youtube-dl \
  zsh

sudo dpkg-reconfigure wireshark-common
sudo usermod -a -G wireshark $USER
sudo chsh -s /bin/zsh $USER

mkdir ~/Projects
git clone git://github.com/ggustafsson/Dot-Files.git ~/Projects/Dot\ Files
git clone git://github.com/ggustafsson/Ninja-Color-Scheme.git ~/Projects/Ninja\ Color\ Scheme

ln -s ~/Projects/Dot\ Files/Scripts
ln -s ~/Projects/Dot\ Files/gitconfig ~/.gitconfig
ln -s ~/Projects/Dot\ Files/gitignore_global ~/.gitignore_global
ln -s ~/Projects/Dot\ Files/ssh_config ~/.ssh/config
ln -s ~/Projects/Dot\ Files/tmux.conf ~/.tmux.conf
ln -s ~/Projects/Dot\ Files/vimrc ~/.vimrc
ln -s ~/Projects/Dot\ Files/zshenv ~/.zshenv
ln -s ~/Projects/Dot\ Files/zshrc ~/.zshrc

mkdir ~/.vim
mkdir ~/.vim/autoload
mkdir ~/.vim/backups
mkdir ~/.vim/bundle
mkdir ~/.vim/colors
mkdir ~/.vim/undos

ln -s ~/Projects/Dot\ Files/vim/snippets ~/.vim/
ln -s ~/Projects/Dot\ Files/vim/syntax ~/.vim/

~/Scripts/vimp

ln -s ~/.vim/pathogen/autoload/pathogen.vim ~/.vim/autoload/
ln -s ~/Projects/Ninja\ Color\ Scheme/colors/ninja.vim ~/.vim/colors/
