#!/bin/bash

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

# Description: This script configures a Ubuntu system the way i like.

# Usage: ubunutusetup

rm ~/examples.desktop

sudo apt-get install \
  cowsay \
  dsniff \
  ettercap-graphical \
  ffmpeg \
  figlet \
  flac \
  gawk \
  git \
  gparted \
  hping3 \
  html2text \
  imagemagick \
  irssi \
  kismet \
  lame \
  links \
  ncftp \
  netperf \
  nginx \
  nmap \
  offline-imap \
  openssh-server \
  php5 \
  ruby \
  sshguard \
  tmux \
  transmission \
  tree \
  tshark \
  vim-nox \
  vorbis-tools \
  wireshark \
  xbmc \
  youtube-dl \
  zsh

sudo dpkg-reconfigure wireshark-common
sudo usermod -a -G wireshark $USER
sudo chsh -s /bin/zsh $USER

mkdir ~/Projects
git clone git@github.com:ggustafsson/Dot-Files.git ~/Projects/Dot\ Files
ln -s ~/Projects/Dot\ Files/Scripts ~/Scripts

~/Scripts/dotfiles
