#!/bin/bash

rm ~/examples.desktop

sudo apt-get install \
  git \
  ncftp \
  nmap \
  ruby \
  tree \
  vim-nox \
  zsh

sudo chsh -s /bin/zsh $USER

mkdir ~/Projects
git clone git@github.com:ggustafsson/Dot-Files.git ~/Projects/Dot\ Files
git clone git@github.com:ggustafsson/Ninja-Color-Scheme.git ~/Projects/Ninja\ Color\ Scheme

ln -s ~/Projects/Dot\ Files/Scripts
ln -s ~/Projects/Dot\ Files/gitconfig ~/.gitconfig
ln -s ~/Projects/Dot\ Files/gitignore_global ~/.gitignore_global
ln -s ~/Projects/Dot\ Files/tmux.conf ~/.tmux.conf
ln -s ~/Projects/Dot\ Files/vimrc ~/.vimrc
ln -s ~/Projects/Dot\ Files/zshenv ~/.zshenv
ln -s ~/Projects/Dot\ Files/zshrc ~/.zshrc

mkdir ~/.vim
mkdir ~/.vim/autoload
mkdir ~/.vim/backups
mkdir ~/.vim/bundle
mkdir ~/.vim/colors
mkdir ~/.vim/undos

ln -s ~/Projects/Dot\ Files/vim/snippets ~/.vim/
ln -s ~/Projects/Dot\ Files/vim/syntax ~/.vim/

~/Scripts/vimp

ln -s ~/.vim/pathogen/autoload/pathogen.vim ~/.vim/autoload/
ln -s ~/Projects/Ninja\ Color\ Scheme/colors/ninja.vim ~/.vim/colors/
