#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

# Description: This script backs up several directories to a server with rsync
# through ssh.

# Usage: backup2s

server=hoth
destination=/media/external

directories=(
  /Volumes/External/Disc\ Images
  /Volumes/External/Documentaries
  /Volumes/External/Movies
  /Volumes/External/Series
  ~/Music/FLAC
  ~/Music/MP3
  ~/YouTube
)

echo "Backing up directories to server '$server'."

for directory in $directories; do
  print -P "\n%B%F{green}Backing up directory $directory.%f%b"
  rsync --archive --delete --human-readable --progress $directory -e ssh ${server}:$destination
done
