#!/usr/bin/env zsh

# Description: This script backs up a few specific directories/files to device.
#
# Usage: backup
#
# Written by Göran Gustafsson (gustafsson.g at gmail.com).
# License: BSD 3-Clause.

destination=/Volumes/Keychain

backup_objects=(
  ~/.ssh
  ~/Development
  ~/Documents
  ~/Dropbox
  ~/Golang
  ~/Library/Application\ Support/OpenEmu
  ~/Library/Safari/Bookmarks.plist
  ~/Movies
  ~/Music/MP3
  ~/Pictures
  ~/Projects
  ~/Storage
  ~/Web\ Archives
)

if [[ ! -d $destination ]]; then
  echo "Directory '${destination}' does not exist! Exiting..."
  exit 1
fi

echo "Backing up to directory '${destination}'."

for object in $backup_objects; do
  if [[ -a $object ]]; then
    print -P "\n%B%F{green}Backing up: ${object/${HOME}/~}%f%b"
    rsync --archive --delete --human-readable --verbose \
      --exclude=Dropbox/.dropbox.cache \
      --exclude=Dropbox/Public \
      --exclude=Dropbox/Shared\ Files \
      $object $destination
  else
    echo "\nObject '${object}' not found! Exiting..."
    exit 1
  fi
done

echo "\nUnmounting external device."
while true; do
  sleep 5
  diskutil eject $destination && exit
done
