#!/usr/bin/env zsh

# Original script created by Zach Holman:
#   <https://github.com/holman/dotfiles/blob/master/bin/backup>.
# Modified by Göran Gustafsson <gustafsson.g@gmail.com>.

# Description: This script mounts an encrypted dmg file (sparseimage), backs
# up a few specific directories to it and then unmounts the image file.

# Usage: backup

device_name=Keychain
encrypted_image=/Volumes/$device_name/Backup.sparseimage
backup_destination=/Volumes/Backup

directories=(
  Development
  Documents
  Dropbox
  Library/Safari/Bookmarks.plist
  Movies
  Music/FLAC
  Music/GBS
  Music/NSFe
  Music/Ringtones
  Pictures
  Projects
  School
  Storage
  Web\ Archives
  YouTube
)

if [[ ! -f $encrypted_image ]]; then
  echo "File '$encrypted_image' does not exist!"
  return 1
fi

echo "Mounting encrypted image file."
hdiutil attach -noverify $encrypted_image

if [[ ! -d $backup_destination ]]; then
  echo "\nDirectory '$backup_destination' does not exist!"
  return 1
fi

for directory in $directories; do
  print -P "\n%B%F{green}Backing up directory ~/$directory.%f%b"
  rsync --archive --delete --exclude=Dropbox/.dropbox.cache --human-readable --verbose ~/$directory $backup_destination
done

echo "\nUnmounting encrypted image file and device."
hdiutil detach $backup_destination && diskutil eject $device_name
