#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

# Description: Simple script to turn Bluetooth off.

# Usage: blueoff

osascript -e '
  tell application "System Preferences"
    reveal pane "com.apple.preferences.Bluetooth"
  end tell
  tell application "System Events" to tell process "System Preferences"
    tell window "Bluetooth"
      tell button 6
        if name is "Turn Bluetooth Off" then click
      end tell
    end tell
  end tell
  delay 2
  quit application "System Preferences"
' && echo "Bluetooth is turned off."
