#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

# Description: This script makes it easy to search with the built in
# dictionary application under OS X.

# Usage: dict <word>

if [[ $# -eq 1 ]]; then
  open "dict://$*"
else
  echo "Usage: $0:t [WORD]..."
fi
