#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

# Description: This script opens up a new Terminal window and moves it to my
# external display.

# Usage: eterm

osascript -e '
  tell application "System Events"
    tell application process "Terminal"
      set frontmost to true
      click menu item "New Window with Settings - Default" of menu 1 of menu item "New Window" of menu 1 of menu bar item "Shell" of menu bar 1
    end tell

    tell application "Terminal"
      set position of window 1 to {1440, 22}
    end tell
  end tell' > /dev/null
