#!/usr/bin/env zsh

# Description: This script makes it easy to open the current working directory
# or a specific directory in Finder.

# Usage: f
#        f <path>

# Written by Göran Gustafsson (gustafsson.g at gmail.com).
# License: BSD 3-Clause.

if [[ $# -ge 1 ]]; then
  open -a Finder $*
else
  open .
fi
