#!/usr/bin/env zsh

# Description: This script deletes various space hogging files/directories.
#
# Usage: frees
#
# Written by Göran Gustafsson (gustafsson.g at gmail.com).
# License: BSD 3-Clause.

remove_objects=(
  ~/Library/Application\ Support/com.github.GitHub.ShipIt/update.*(N)
  ~/Library/Caches/Homebrew
  ~/Library/Caches/com.apple.dt.Xcode/Downloads
  ~/Library/Caches/com.spotify.client
  ~/Library/Logs/Homebrew
  ~/Library/Mail\ Downloads
  ~/Library/iTunes/iPhone\ Software\ Updates
)

echo "Deleting unnecessary files."

for object in $remove_objects; do
  if [[ -a $object ]]; then
    echo
    rm -rfv $object
  fi
done
