#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

# Description: This script deletes various space hogging files/directories.

# Usage: frees

remove_objects=(
  /Library/Caches/Homebrew
  ~/Library/Application\ Support/com.github.GitHub.ShipIt/update.*(N)
  ~/Library/Caches/com.apple.dt.Xcode/Downloads
  ~/Library/Caches/com.spotify.client
  ~/Library/Logs/Homebrew
  ~/Library/Mail\ Downloads
  ~/Library/iTunes/iPhone\ Software\ Updates
)

echo "Deleting unnecessary files."

for object in $remove_objects; do
  if [[ -a $object ]]; then
    echo
    rm -rfv $object
  fi
done
