#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

# Description: This script deletes various space hogging files/directories.

# Usage: frees

echo "Deleting useless files."

rm -rf /Library/Caches/Homebrew
rm -rf ~/Library/Application\ Support/com.github.GitHub.ShipIt/update.*(N)
rm -rf ~/Library/Caches/Firefox
rm -rf ~/Library/Caches/Google
rm -rf ~/Library/Caches/com.apple.dt.Xcode/Downloads
rm -rf ~/Library/Caches/com.spotify.client
rm -rf ~/Library/Logs/Homebrew
rm -rf ~/Library/Mail\ Downloads
rm -rf ~/Library/iTunes/iPhone\ Software\ Updates
