#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

# Description: This script executes various things i want to run every time i
# get home.

# Usage: home

osascript -e '
  tell application "System Preferences"
    reveal pane "com.apple.preferences.Bluetooth"
  end tell
  tell application "System Events" to tell process "System Preferences"
    tell window "Bluetooth"
      tell button 6
        if name is "Turn Bluetooth On" then click
      end tell
    end tell
  end tell
  delay 3
  quit application "System Preferences"
'

osascript -e "set volume output volume 38"

transmission=$(osascript -e '
  tell application "System Events"
    count (every process whose name is "Transmission")
  end tell
')
if [[ $transmission -eq 0 ]]; then
  open -a Transmission
fi
