#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

function disable_wifi {
  echo "Turning off WiFi."
  networksetup -setairportpower en0 off
}

function enable_wifi {
  echo -n "Type 'yesiamfuckingsureiwantwifi' to enable WiFi: "
  read areyoufuckingsure
  if [[ $areyoufuckingsure == yesiamfuckingsureiwantwifi ]]; then
    enable_wifi_noninteractive
  else
    print -P "\n%B%F{red}NO WIFI FOR YOU!%f%b"
  fi
}

function enable_wifi_noninteractive {
  networksetup -setairportpower en0 on
}

if [[ $# == 1 ]] && [[ $1 == on ]]; then
  enable_wifi
elif [[ $# == 1 ]] && [[ $1 == on_noninteractive ]]; then
  enable_wifi_noninteractive
elif [[ $# == 1 ]] && [[ $1 == off ]]; then
  disable_wifi
else
  echo "Usage: $0:t [on/on_noninteractive/off]..."
fi

