#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

# Description: This script executes a bunch of commands i run twice every week
# to back things up and keep things up-to-date.

# Usage: maintenance

server=hoth

echo -n "Everything plugged in and ready to go? [y/n] "
read answer

if [[ $answer == (y|yes) ]]; then
  echo -n "Back up Minecraft servers? [y/n] "
  read answer

  if [[ $answer == (y|yes) ]]; then
    echo
    rsync --archive --delete --human-readable --progress -e ssh $server:~/Minecraft\ -\ Creative/ ~/Dropbox/Minecraft/Server\ -\ Creative
    rsync --archive --delete --human-readable --progress -e ssh $server:~/Minecraft\ -\ Survival/ ~/Dropbox/Minecraft/Server\ -\ Survival
  fi

  echo
  offlineimap
  echo
  brew update
  brew upgrade
  brew cleanup
  echo
  gem update --system
  gem update
  echo
  gemfix
  echo
  otherd
  echo
  vimp
  echo
  frees
  echo
  backup

  open -a "App Store"
  open -a Xcode
else
  echo "\nBye bye!"
fi
