#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

# Description: This script executes a bunch of commands i run frequently to
# back things up and keep things up-to-date.

# Usage: maintenance

echo -n "Everything plugged in and ready to go? [y/n] "
read answer

if [[ $answer == (y|yes) ]]; then
  echo -n "Back up Minecraft servers? [y/n] "
  read answer

  if [[ $answer == (y|yes) ]]; then
    echo
    rsync --archive --delete --human-readable --progress -e ssh hoth:'~/Minecraft\ -\ Creative/' ~/Storage/Game\ Files/Minecraft/Server\ -\ Creative/
    echo
    rsync --archive --delete --human-readable --progress -e ssh hoth:'~/Minecraft\ -\ Survival/' ~/Storage/Game\ Files/Minecraft/Server\ -\ Survival/
  fi

  echo
  brew update
  brew upgrade
  brew cleanup
  brew linkapps --local
  echo
  gem update --system
  gem update
  gem cleanup
  echo
  gemfix
  echo
  dl_misc
  echo
  dl_vim
  echo
  frees
  echo
  backup

  open -a "App Store"
else
  echo "\nBye bye\!"
fi
