#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

# Description: This script executes a bunch of commands i run frequently to
# back things up and keep things up-to-date.

# Usage: maintenance

server_local=hoth
server_external=fulknark

echo -n "Everything plugged in and ready to go? [y/n] "
read answer

if [[ $answer == (y|yes) ]]; then
  echo -n "Back up Minecraft servers? [y/n] "
  read answer

  if [[ $answer == (y|yes) ]]; then
    echo -n "Are you at home right now? [y/n] "
    read answer

    if [[ $answer == (y|yes) ]]; then
      echo
      rsync --archive --delete --human-readable --progress -e ssh $server_local:'~/Minecraft\ -\ Creative/' ~/Dropbox/Minecraft/Server\ -\ Creative/
      echo
      rsync --archive --delete --human-readable --progress -e ssh $server_local:'~/Minecraft\ -\ Survival/' ~/Dropbox/Minecraft/Server\ -\ Survival/
    else
      echo
      rsync --archive --delete --human-readable --progress -e ssh $server_external:'~/Minecraft\ -\ Creative/' ~/Dropbox/Minecraft/Server\ -\ Creative/
      echo
      rsync --archive --delete --human-readable --progress -e ssh $server_external:'~/Minecraft\ -\ Survival/' ~/Dropbox/Minecraft/Server\ -\ Survival/
    fi
  fi

  echo
  offlineimap
  echo
  brew update
  brew upgrade
  brew cleanup
  echo
  gem update --system
  gem update
  echo
  gemfix
  echo
  otherd
  echo
  vimp
  echo
  frees
  echo
  backup

  open -a "App Store"
  open -a Xcode
else
  echo "\nBye bye!"
fi
