#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

# Description: This script converts man pages to PDF files with Preview.app.

# Usage: man2pdf <man>
#        man2pdf <man> <man> ...

if [[ ! $# -gt 0 ]]; then
  echo "Usage: $0:t [MAN PAGE(S)]..."
  exit
fi

for argument in $*; do
  man -t $argument | open -f -a Preview
done
