#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

# Description: This script 

# Usage: merge

echo "Merging all windows for Safari and Terminal."

# "set frontmost to true" is needed if not executed from Terminal.
osascript -e '
  tell application "System Events"
    tell application process "Terminal"
      click menu item "Merge All Windows" of menu 1 of menu bar item "Window" of menu bar 1
    end tell
  end tell' > /dev/null

osascript -e '
  tell application "System Events"
    tell application process "Safari"
      click menu item "Merge All Windows" of menu 1 of menu bar item "Window" of menu bar 1
    end tell
  end tell' > /dev/null
