#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

# Description: This script changes a few settings that can only be changed
# through the terminal and i don't want to run the commands manually.

# Usage: osxdefaults

# Put the Dock at the left/top (i use the Dock on the top left side).
defaults write com.apple.dock pinning -string start
killall Dock

# Remove the Spotlight icon in the menu bar.
sudo chmod 600 /System/Library/CoreServices/Search.bundle/Contents/MacOS/Search
killall SystemUIServer

# Disable window animations.
defaults write NSGlobalDomain NSAutomaticWindowAnimationsEnabled -bool NO

# Disable all Mail animations.
defaults write com.apple.Mail DisableReplyAnimations -bool YES
defaults write com.apple.Mail DisableSendAnimations -bool YES

# Disable webpage screenshots in Safari.
defaults write com.apple.Safari DebugSnapshotsUpdatePolicy -int 2
rm -rf ~/Library/Caches/com.apple.Safari/Webpage\ Previews

# Make the delete key work again.
defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2BackspaceKeyNavigationEnabled -bool YES
