#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

# Description: This script changes a few settings that can only be changed
# through the terminal and i don't want to run the commands manually.

# Usage: osxsetup

# Put the Dock at the left/top (i use the Dock on the top left side).
defaults write com.apple.dock pinning -string start
killall Dock

# Disable window animations.
defaults write NSGlobalDomain NSAutomaticWindowAnimationsEnabled -bool NO

# Disable all Mail animations.
defaults write com.apple.Mail DisableReplyAnimations -bool YES
defaults write com.apple.Mail DisableSendAnimations -bool YES

# Disable webpage screenshots in Safari.
defaults write com.apple.Safari DebugSnapshotsUpdatePolicy -int 2
rm -rf ~/Library/Caches/com.apple.Safari/Webpage\ Previews

# Make the delete key work again.
defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2BackspaceKeyNavigationEnabled -bool YES

# Unhide the ~/Library folder.
chflags nohidden ~/Library

# Display 24-hour clock at login/lock screen.
sudo defaults write /Library/Preferences/.GlobalPreferences AppleLocale en_GB

# Stop Mac OS X from overriding hostname.
sudo scutil --set HostName tatooine.lan

# Remove left over file. https://discussions.apple.com/thread/4213550
sudo rm /System/Library/LaunchAgents/com.apple.afpstat.plist
