#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

# Description: This script changes a few settings that can only be changed
# through the terminal and i don't want to run the commands manually.

# Usage: osxsetup

# Unhide the ~/Library folder.
chflags nohidden ~/Library

# Display 24-hour clock at login/lock screen.
sudo defaults write /Library/Preferences/.GlobalPreferences AppleLocale en_GB

# Stop Mac OS X from overriding hostname.
sudo scutil --set HostName tatooine.lan

# Remove left over file. https://discussions.apple.com/thread/4213550
sudo rm /System/Library/LaunchAgents/com.apple.afpstat.plist
