#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

# Description: This script configures a OS X system the way i like.

# Usage: osxsetup

chflags nohidden ~/Library

git clone git@github.com:mxcl/homebrew.git ~/Downloads/homebrew
sudo mv ~/Downloads/homebrew /usr/local

sudo /usr/local/bin/brew tap homebrew/dupes
sudo /usr/local/bin/brew tap josegonzalez/homebrew-php

sudo /usr/local/bin/brew install \
  bash \
  coreutils \
  cowsay \
  curl \
  dsniff \
  ettercap \
  ffmpeg \
  figlet \
  flac \
  gawk \
  git \
  gnu-sed \
  hping \
  html2text \
  imagemagick --without-x \
  imagesnap \
  irssi \
  kismet \
  lame \
  links \
  macvim \
  ncftp \
  netperf \
  nginx \
  nmap \
  offline-imap \
  openssh \
  php55 \
  python \
  python3 \
  rsync \
  ruby \
  svtplay-dl \
  tmux \
  tree \
  vim \
  vorbis-tools \
  wget \
  wireshark \
  youtube-dl \
  zsh

~/Scripts/dotfiles
