#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

# Description: This script executes various things i want to run ever time
# before i leave my home.

# Usage: outside

osascript -e "set volume output volume 0"

osascript -e '
  tell application "System Preferences"
    reveal pane "com.apple.preferences.Bluetooth"
  end tell
  tell application "System Events" to tell process "System Preferences"
    tell window "Bluetooth"
      tell button 6
        if name is "Turn Bluetooth Off" then click
      end tell
    end tell
  end tell
  delay 3
  quit application "System Preferences"
'

transmission=$(osascript -e '
  tell application "System Events"
    count (every process whose name is "Transmission")
  end tell
')
if [[ $transmission -ge 1 ]]; then
  osascript -e 'tell application "Transmission" to quit'
fi
