#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

# Description: This script opens a file or several files in Quick Look.

# Usage: ql <file(s)>

if [[ ! $# -gt 0 ]]; then
  echo "Usage: ${0:t} [FILENAME(S)]..."
  exit
fi

qlmanage -p $* &> /dev/null
