#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

# Description: Easily delete .DS_Store files.

# Usage: rmds
#        rmds <path>

if [[ $# -eq 0 ]]; then
  find . -type f -name .DS_Store -exec rm -v "{}" \;
elif [[ $# -eq 1 ]]; then
  find $1 -type f -name .DS_Store -exec rm -v "{}" \;
else
  echo "Usage: ${0:t} [PATH]..."
fi
