#!/usr/bin/env zsh

# Description: Scan the LAN for open network services (FTP, SSH, HTTP, HTTPS,
# SMB, AFP and VNC).
#
# Dependencies: nmap
#
# Usage: servf
#
# Written by Göran Gustafsson (gustafsson.g at gmail.com).
# License: BSD 3-Clause.

# Yes, /24 is hard-coded. Who cares?!
network=$(ifconfig en0 | \
  awk 'NR == 4 { print $2 }' | \
  sed "s/.\([0-9]*\)$/.0/g")/24

# 21   = FTP
# 22   = SSH
# 80   = HTTP
# 443  = HTTPS
# 445  = SMB
# 445  = SMB
# 548  = AFP
# 5900 = VNC
# 8080 = Alternative HTTP
ports="21,22,80,443,445,548,5900,8080"

echo "Scanning network $network"

results=$(nmap -sT $network -p $ports --open 2> /dev/null | \
  egrep -v "(Host is up|Not shown)" | \
  tail -n +3 | head -n -2)

if [[ ! -z $results ]]; then
  echo "\n$results"
else
  echo "\nNo services found on network!"
fi
