#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

# Description: This script configures a OS X system the way i like.

# Usage: setup_osx

sudo echo "Testing if this user is allowed to use sudo."

if [[ $? -eq 1 ]]; then
  echo "User is not allowed to use sudo! Exiting..."
  return 1
fi

if [[ ! -f ~/.ssh/id_rsa ]]; then
  echo "Install the SSH key first! Exiting..."
  return 1
fi

echo -n "\nWhat hostname do you want? "
read new_hostname

if [[ -z $new_hostname ]]; then
  echo "No hostname supplied! Exiting..."
  return 1
fi

# Override hostname from DHCP server.
sudo scutil --set HostName $new_hostname

# Enable backspace in Safari again.
defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2BackspaceKeyNavigationEnabled -bool YES

# Hide the Public folder.
chflags hidden ~/Public

# Install Xcode Command Line Tools.
echo
xcode-select --install

echo
git clone git://github.com/mxcl/homebrew.git ~/Downloads/homebrew
sudo mv ~/Downloads/homebrew /usr/local

/usr/local/bin/brew tap homebrew/dupes

/usr/local/bin/brew install \
  bash \
  coreutils \
  cowsay \
  curl \
  ffmpeg \
  flac \
  gawk \
  git \
  gnu-sed \
  html2text \
  imagemagick --without-x \
  imagesnap \
  lame \
  links \
  macvim \
  ncftp \
  netperf \
  nmap \
  openssh \
  p7zip \
  python \
  python3 \
  rsync \
  ruby \
  svtplay-dl \
  tmux \
  tree \
  unrar \
  vim \
  vorbis-tools \
  weechat \
  wget \
  youtube-dl \
  zsh

echo "Adding new Zsh to login shells:"
echo "/usr/local/bin/zsh" | sudo tee -a /etc/shells

ln -s /usr/local/bin/gdircolors /usr/local/bin/dircolors
ln -s /usr/local/bin/ghead /usr/local/bin/head
ln -s /usr/local/bin/gls /usr/local/bin/ls
ln -s /usr/local/bin/gmkdir /usr/local/bin/mkdir
ln -s /usr/local/bin/gsed /usr/local/bin/sed
ln -s /usr/local/bin/gsort /usr/local/bin/sort
ln -s /usr/local/bin/gtail /usr/local/bin/tail
ln -s /usr/local/bin/guniq /usr/local/bin/uniq
ln -s /usr/local/bin/gwc /usr/local/bin/wc

export GEM_HOME=~/.gem/ruby

echo
/usr/local/bin/gem install terminal-notifier
/usr/local/bin/pip install mutagen

echo
~/Scripts/setup_dotfiles
~/Scripts/dl_misc
