#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

# Description: This script configures a OS X system the way i like.

# Usage: setup_osx

if sudo -n test >& /dev/null; then
  echo "User is not allowed to use sudo! Exiting..."
  return 1
fi

if ! type -p git >& /dev/null; then
  echo "Install Xcode and 'Command Line Tools' first! Exiting..."
  return 1
fi

chflags nohidden ~/Library

git clone git@github.com:mxcl/homebrew.git ~/Downloads/homebrew
sudo mv ~/Downloads/homebrew /usr/local

sudo /usr/local/bin/brew tap homebrew/dupes

sudo /usr/local/bin/brew install \
  bash \
  coreutils \
  cowsay \
  curl \
  ffmpeg \
  flac \
  gawk \
  git \
  gnu-sed \
  html2text \
  imagemagick --without-x \
  imagesnap \
  irssi \
  lame \
  links \
  macvim \
  ncftp \
  nmap \
  openssh \
  python \
  python3 \
  rsync \
  ruby \
  svtplay-dl \
  tmux \
  tree \
  vim \
  vorbis-tools \
  wget \
  youtube-dl \
  zsh

ln -s /usr/local/bin/gdircolors /usr/local/bin/dircolors
ln -s /usr/local/bin/ghead /usr/local/bin/head
ln -s /usr/local/bin/gls /usr/local/bin/ls
ln -s /usr/local/bin/gmkdir /usr/local/bin/mkdir
ln -s /usr/local/bin/gsed /usr/local/bin/sed
ln -s /usr/local/bin/gsort /usr/local/bin/sort
ln -s /usr/local/bin/gtail /usr/local/bin/tail
ln -s /usr/local/bin/guniq /usr/local/bin/uniq
ln -s /usr/local/bin/gwc /usr/local/bin/wc

~/Scripts/setup_dotfiles
~/Scripts/dl_misc
