#!/usr/bin/env zsh

# Description: This script configures a OS X system the way i like.
#
# Usage: setup_osx
#
# Written by Göran Gustafsson (gustafsson.g at gmail.com).
# License: BSD 3-Clause.

sudo echo "Testing if this user is allowed to use sudo."
if [[ $? -eq 1 ]]; then
  echo "User is not allowed to use sudo! Exiting..."
  exit 1
fi

echo "Testing if permissions on /usr/local are OK (SIP)."
mkdir -p /usr/local/perm_test
if [[ $? -eq 1 ]]; then
  echo "User is not allowed to write! Exiting..."
  exit 1
else
  rm -rf /usr/local/perm_test
fi

if [[ ! -d /Applications/Xcode.app ]]; then
  echo "Install Xcode first! Exiting..."
  exit 1
fi

if [[ ! -f ~/.ssh/id_rsa ]]; then
  echo "Install the SSH key first! Exiting..."
  exit 1
fi

echo -n "\nWhat hostname do you want? "
read new_hostname
if [[ -z $new_hostname ]]; then
  echo "No hostname supplied! Skipping..."
else
  # Override hostname from DHCP server.
  sudo scutil --set HostName $new_hostname
fi

# Check for updates daily instead of once a week.
sudo defaults write /Library/Preferences/com.apple.SoftwareUpdate ScheduleFrequency -int 1

# Hide and unhide folders in Finder.
chflags hidden ~/Public
chflags nohidden ~/Library

# Install Xcode Command Line Tools.
echo
xcode-select --install

echo "Press enter when Command Line Tools are installed and tested."
read answer

git clone https://github.com/mxcl/homebrew.git ~/Downloads/homebrew
sudo mv ~/Downloads/homebrew/{*,.*} /usr/local/

/usr/local/bin/brew tap homebrew/dupes
/usr/local/bin/brew install \
  bash \
  coreutils \
  curl \
  ffmpeg \
  flac \
  gawk \
  git \
  gnu-sed \
  gnupg2 \
  gnuplot \
  golang \
  html2text \
  imagemagick --without-x \
  imagesnap \
  lame \
  ncftp \
  nmap \
  openssh \
  python --build-from-source \
  python3 \
  renameutils \
  rsync \
  ruby \
  svtplay-dl \
  tmux \
  tree \
  vim \
  vorbis-tools \
  weechat --with-lua --with-perl --with-python --with-ruby \
  wget \
  youtube-dl \
  zsh

echo "Adding new Zsh to login shells:"
echo "/usr/local/bin/zsh" | sudo tee -a /etc/shells

ln -s /usr/local/bin/ghead /usr/local/bin/head
ln -s /usr/local/bin/gls /usr/local/bin/ls
ln -s /usr/local/bin/gsed /usr/local/bin/sed
ln -s /usr/local/bin/gsort /usr/local/bin/sort
ln -s /usr/local/bin/gtail /usr/local/bin/tail
ln -s /usr/local/bin/guniq /usr/local/bin/uniq
ln -s /usr/local/bin/gwc /usr/local/bin/wc

echo
/usr/local/bin/pip install mutagen simpy

cd /usr/local/lib/python3.*
for directory in /usr/local/lib/python2.*/site-packages/simpy*; do
  ln -s $directory
done

echo
~/Scripts/setup_dotfiles
