#!/usr/bin/env zsh

# Description: This script configures a OS X system the way I like.
#
# Usage: setup-osx
#
# Written by Göran Gustafsson (gustafsson.g at gmail.com).
# License: BSD 3-Clause.

sudo test
if [[ $? -eq 1 ]]; then
  echo "User is not allowed to use sudo! Exiting..."
  exit 1
fi

# Check write permission for homebrew (SIP blocking?).
mkdir -p /usr/local/perm_test
if [[ $? -eq 1 ]]; then
  echo "User is not allowed to write to /usr/local! Exiting..."
  exit 1
else
  rm -rf /usr/local/perm_test
fi

if [[ ! -d /Applications/Xcode.app ]]; then
  echo "Install Xcode first! Exiting..."
  exit 1
fi

# Check for GitHub keys.
if [[ ! -f ~/.ssh/id_rsa ]]; then
  echo "Install the SSH key first! Exiting..."
  exit 1
fi

chflags hidden ~/Public
chflags nohidden ~/Library

# Check for updates daily instead of once a week.
sudo defaults write /Library/Preferences/com.apple.SoftwareUpdate ScheduleFrequency -int 1

# Override hostname from DHCP server.
echo -n "What hostname do you want? "
read new_hostname
if [[ -z $new_hostname ]]; then
  echo "No hostname supplied! Skipping..."
else
  sudo scutil --set HostName $new_hostname
fi
echo

xcode-select --install
echo -n "Press 'Return' when Command Line Tools are installed..."
read -s wait_for_input
echo

git clone https://github.com/mxcl/homebrew.git ~/Downloads/homebrew
sudo mv ~/Downloads/homebrew/{*,.*} /usr/local/

/usr/local/bin/brew tap homebrew/dupes
/usr/local/bin/brew install \
  bash \
  coreutils \
  curl \
  ffmpeg \
  flac \
  gawk \
  git \
  gnu-sed \
  gnupg2 \
  gnuplot \
  golang \
  html2text \
  imagemagick --without-x \
  imagesnap \
  lame \
  links \
  ncftp \
  neovim/neovim/neovim \
  nmap \
  openssh \
  python --build-from-source \
  python3 \
  renameutils \
  rsync \
  ruby \
  svtplay-dl \
  tmux \
  tree \
  vim \
  vorbis-tools \
  weechat --with-lua --with-perl --with-python --with-ruby \
  wget \
  youtube-dl \
  zsh

/usr/local/bin/pip3 install mutagen simpy

echo "/usr/local/bin/zsh" | sudo tee -a /etc/shells

ln -s /usr/local/bin/{g,}head
ln -s /usr/local/bin/{g,}ls
ln -s /usr/local/bin/{g,}sed
ln -s /usr/local/bin/{g,}sort
ln -s /usr/local/bin/{g,}tail
ln -s /usr/local/bin/{g,}uniq
ln -s /usr/local/bin/{g,}wc

ln -s ~/Projects/Dot\ Files/Scripts ~/
ln -s ~/Projects/Dot\ Files/gitconfig ~/.gitconfig
ln -s ~/Projects/Dot\ Files/gitignore_global ~/.gitignore_global
ln -s ~/Projects/Dot\ Files/hammerspoon ~/.hammerspoon
ln -s ~/Projects/Dot\ Files/timrc ~/.timrc
ln -s ~/Projects/Dot\ Files/tmux.conf ~/.tmux.conf
ln -s ~/Projects/Dot\ Files/vimrc ~/.vimrc
ln -s ~/Projects/Dot\ Files/zshenv ~/.zshenv
ln -s ~/Projects/Dot\ Files/zshrc ~/.zshrc

ln -s ~/Projects/IP-Kalkylatorn/ipkalk ~/Scripts/
ln -s ~/Projects/Tim/tim ~/Scripts/

mkdir -p ~/.config
ln -s ~/.vim ~/.config/nvim
ln -s ~/.vimrc ~/.config/nvim/init.vim

sudo cp ~/Projects/Dot\ Files/motd-osx /etc/motd

echo
~/Scripts/fetch-vim
