#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

# Description: This script searches the current network (always /24) for open
# network shares on port 445 (SMB/CIFS).

# Dependencies: nmap

# Usage: smbf

ip=$(ifconfig en0 | sed -n 's/^[ \t]*//;s/inet //p' | awk '{ print $1 }')
port=445

echo "Scanning for network shares."

results=$(nmap -sT ${ip}/24 -p $port --open 2> /dev/null | egrep "(Nmap scan report for|$port/tcp)")

if [[ ! -z $results ]]; then
  echo "\n$results"
else
  echo "\nNo network shares found!"
fi
