#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

# Description: This script makes it easy to connect to VNC servers.

# Usage: vnc <ip/dns>

if [[ ! $# -eq 1 ]]; then
  echo "Usage: $0:t [IP/DNS]..."
  exit
fi

open "vnc://$1"
