#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

# Description: This script modifies the group owner and file permissions on
# the /dev/bpf* files so i can run Wireshark under OS X.
#
# I have this in ~/.zshrc to make every wireshark command an alias that
# executes this script before running the original command:
#
# wireshark=(/usr/local/Cellar/wireshark/*/bin/*(N:t))
#
# for command in $wireshark; do
#   alias $command="wiresharkfix $command"
# done

# Usage: <wireshark command>

if [[ ! -w /dev/bpf1 ]]; then
  sudo chgrp wireshark /dev/bpf*
  sudo chmod 660 /dev/bpf*
fi

exec $*
