#!/usr/bin/env python3
"""
Description: #A

Usage: #B

Creator: Göran Gustafsson (gustafsson.g at gmail.com)
License: BSD 3-Clause
"""


def main():
    """#C"""
    #D


if __name__ == "__main__":
    main()
