" Göran Gustafsson <gustafsson.g@gmail.com>

call pathogen#infect()
call pathogen#helptags()

filetype plugin indent on

syntax enable
colorscheme ninja

set backspace=indent,eol,start
set confirm
set cryptmethod=blowfish
set encoding=utf-8
set formatoptions=cjlnoqrt
set gdefault
set hidden
set nofoldenable
set nowrap
set scrolloff=3
set showbreak=+
set spelllang=en,sv
set timeoutlen=2000
set virtualedit=block

set autoindent
set smartindent

set backup
set backupdir=~/.vim/backups
set directory=~/.vim/backups
set undofile
set undodir=~/.vim/undos

set expandtab
set shiftwidth=2
set softtabstop=2

set history=1000
set undolevels=2000

set hlsearch
set ignorecase
set incsearch
set smartcase

set laststatus=2
set statusline=%(\ %F\ %)
set statusline+=%(%m\ %)
set statusline+=%([%{(&fenc==\"\"?&enc:&fenc)}]\ %)
set statusline+=%(%y\ %)
set statusline+=%(%{&paste?'[paste]':''}\ %)
set statusline+=%=
set statusline+=%(%v,\ %)
set statusline+=%(%l/%L\ %)
set tabline=%!TabLine()

set list
set listchars=tab:>-,trail:-,precedes:<,extends:>

set numberwidth=3
set relativenumber

set splitbelow
set splitright

set t_vb=
set visualbell

set wildmode=longest,list
set wildignore=*.doc,*.pdf,.DS_Store
set wildignore+=*.bmp,*.gif,*.ico,*.jpg,*.jpeg,*.png,*.svg,*.tiff
set wildignore+=*.flac,*.nsf,*.nsfe,*.m4r,*.mp3,*.ogg,*.wav
set wildignore+=*.avi,*.flv,*.f4v,*.mkv,*.mov,*.mpg,*.mpeg,*.mp4,*.m4v,*.wmv
set wildignore+=*.dmg,*.iso,*.rar,*.tar,*.tar.bz2,*.tar.gz,*.zip,*.7z

if has("gui_running")
  set guicursor+=a:blinkon0
  set guioptions=cgt
  set showcmd

  function! FontSetup()
    set guifont=Inconsolata:h14
    set linespace=1

    set columns=185
    set lines=44
  endfunction

  if !exists("g:dont_load_again")
    call FontSetup()

    let g:dont_load_again = 1
  endif
else
  set mouse=v
  set title
endif

if has("mac")
  let g:gist_clip_command = "pbcopy"
endif

let g:gist_open_browser_after_post = 1
let g:mapleader = ","
let g:nyancat_display_statusline = 1

let g:gundo_help = 0
let g:gundo_preview_statusline = " Gundo Preview"
let g:gundo_tree_statusline = " Gundo Tree"

let g:html_ignore_folding = 1
let g:html_number_lines = 0

let g:LustyExplorerDefaultMappings = 0
let g:LustyJugglerDefaultMappings = 0

let g:minesweeper_custom_colors = 1
let g:minesweeper_statusline = " MineSweeper"
let g:minesweeper_title = "MineSweeper"

let g:NERDCreateDefaultMappings = 0
let g:NERDMenuMode = 0

let g:NERDTreeAutoCenter = 0
let g:NERDTreeDirArrows = 0
let g:NERDTreeMinimalUI = 1
let g:NERDTreeStatusline = " NERDTree"

command! -nargs=? Helpt tab help <args>
cabbrev helpt Helpt

cabbrev Q  q
cabbrev W  w
cabbrev WQ wq
cabbrev Wq wq
cabbrev wQ wq

if has("gui_running")
  nnoremap <Leader>fa :call FancyView()<CR>
endif

if has("mac")
  nnoremap <Leader>fi :silent !open "%:p:h"<CR>
  nnoremap <Leader>op :silent !open -a Safari "%"<CR>
endif

nnoremap <Leader>bd :call BufferDelete()<CR>
nnoremap <Leader>cc :call ColorColumn()<CR>
nnoremap <Leader>cd :cd %:p:h<CR>:pwd<CR>
nnoremap <Leader>do :LustyFilesystemExplorer ~/Documents/Text\ Files<CR>
nnoremap <Leader>ed :LustyFilesystemExplorerFromHere<CR>
nnoremap <Leader>eh :LustyFilesystemExplorer ~<CR>
nnoremap <Leader>ft :set filetype=
nnoremap <Leader>ga :Gist -a<CR>
nnoremap <Leader>gg :Gist<CR>
nnoremap <Leader>gu :GundoToggle<CR>
nnoremap <Leader>in :-read ~/.vim/snippets/
nnoremap <Leader>la :!ls -lFha "%:p:h"<CR>
nnoremap <Leader>li :set list!<CR>
nnoremap <Leader>ll :!ls -lFh "%"<CR>
nnoremap <Leader>ls :!ls -lFh "%:p:h"<CR>
nnoremap <Leader>mi :MineSweeper normal<CR>
nnoremap <Leader>ne :enew<CR>
nnoremap <Leader>nu :call LineNumber()<CR>
nnoremap <Leader>ny :Nyancat2<CR>
nnoremap <Leader>pa :set paste!<CR>
nnoremap <Leader>pw :edit ~/Documents/Text\ Files/Passwords.blowfish<CR>
nnoremap <Leader>re :%s//c<Left><Left>
nnoremap <Leader>rs :source ~/.vim/session.vim<CR>
nnoremap <Leader>s2 :set expandtab softtabstop=2 shiftwidth=2<CR>
nnoremap <Leader>s4 :set expandtab softtabstop=4 shiftwidth=4<CR>
nnoremap <Leader>s8 :set expandtab softtabstop=8 shiftwidth=8<CR>
nnoremap <Leader>sc :edit ~/Documents/Text\ Files/Scratch\ Notes.txt<CR>
nnoremap <Leader>sh :shell<CR>
nnoremap <Leader>sp :setlocal spell!<CR>
nnoremap <Leader>ss :mksession! ~/.vim/session.vim<CR>
nnoremap <Leader>t2 :set noexpandtab shiftwidth=2 softtabstop=0 tabstop=2<CR>
nnoremap <Leader>t4 :set noexpandtab shiftwidth=4 softtabstop=0 tabstop=4<CR>
nnoremap <Leader>t8 :set noexpandtab shiftwidth=8 softtabstop=0 tabstop=8<CR>
nnoremap <Leader>ta <C-w>T
nnoremap <Leader>tm :edit ~/Documents/Text\ Files/Temporary.blowfish<CR>
nnoremap <Leader>to :edit ~/Documents/Text\ Files/To-do\ List.todo<CR>
nnoremap <Leader>tr :NERDTreeToggle<CR>
nnoremap <Leader>tw :set textwidth=78
nnoremap <Leader>un :edit!<CR>
nnoremap <Leader>vi :edit ~/.vimrc<CR>
nnoremap <Leader>w3 :!~/Scripts/validate "%"<CR>
nnoremap <Leader>wr :set wrap!<CR>
nnoremap <Leader>ws :%s/\s\+$//<CR>:nohlsearch<CR>
nnoremap <Leader>zs :edit ~/.zshrc<CR>

nnoremap vil ^vg_

nnoremap + <C-w>+
nnoremap - <C-w>-
nnoremap > <C-w>>
nnoremap Z <C-w><

nnoremap <Backspace> :nohlsearch<CR>
nnoremap <Tab>       :LustyBufferExplorer<CR>
nnoremap <S-Tab>     :bnext<CR>

nnoremap <Leader><Space> <Plug>NERDCommenterToggle
vnoremap <Leader><Space> <Plug>NERDCommenterToggle

vnoremap <Leader>ga :Gist -a<CR>
vnoremap <Leader>gg :Gist<CR>
vnoremap <Leader>ne y:enew<CR>P
vnoremap <Leader>so :sort<CR>

vnoremap s <Plug>VSurround

vnoremap <Tab>   >gv
vnoremap <S-Tab> <gv

if has("gui_running")
  function! FancyView()
    if &guifont != "Inconsolata:h22"
      set antialias
      set guifont=Inconsolata:h22

      if has("mac")
        set fullscreen
      endif
    else
      if has("mac")
        set nofullscreen
      endif

      call FontSetup()
    endif
  endfunction
endif

function! BufferDelete()
  if &modified
    echohl ErrorMsg
    echomsg "No write since last change. Not closing buffer."
    echohl NONE
  else
    let s:total_nr_buffers = len(filter(range(1, bufnr('$')), 'buflisted(v:val)'))

    if s:total_nr_buffers == 1
      bdelete
      echo "Buffer deleted. Created new buffer."
    else
      bprevious
      bdelete #
      echo "Buffer deleted."
    endif
  endif
endfunction

function! ColorColumn()
  if empty(&colorcolumn)
    echo "colorcolumn=79"
    setlocal colorcolumn=79
  elseif &colorcolumn == "79"
    echo "colorcolumn=73"
    setlocal colorcolumn=73
  else
    echo "colorcolumn="
    setlocal colorcolumn=
  endif
endfunction

function! LineNumber()
  if &relativenumber == 1
    echo "set number"
    set number
  elseif &number == 1
    echo "set nonumber"
    set nonumber
  else
    echo "set relativenumber"
    set relativenumber
  endif
endfunction

function! TabLine()
  let label = ''
  let i = 1

  while i <= tabpagenr('$')
    let buflist = tabpagebuflist(i)
    let winnr = tabpagewinnr(i)
    let tabnr = tabpagewinnr(i,'$')
    let label .= '%' . i . 'T'
    let label .= (i == tabpagenr() ? '%#TabLineSel#' : '%#TabLine#')
    let label .= ' '
    let label .= (tabnr > 1 ? tabnr : '')
    let bufnr = buflist[winnr - 1]

    if getbufvar(bufnr, "&modified")
      let label .= '+ '
    elseif tabnr > 1
      let label .= ' '
    endif

    let file = bufname(bufnr)
    let buftype = getbufvar(bufnr, 'buftype')

    if buftype == 'nofile'
      if file =~ '\/.'
        let file = substitute(file, '.*\/\ze.', '', '')
      endif
    else
      let file = fnamemodify(file, ':p:t')
    endif

    if file == ''
      let file = '[No Name]'
    endif

    let label .= file . ' '
    let i = i + 1
  endwhile

  let label .= '%T%#TabLineFill#%='
  return label
endfunction

augroup Main
  autocmd!

  autocmd BufNewFile,BufRead *.todo              setlocal filetype=todo
  autocmd BufNewFile,BufRead INSTALL,README,TODO setlocal filetype=text
  autocmd BufNewFile,BufRead config              setlocal filetype=conf

  autocmd FileType gitcommit          setlocal colorcolumn=73 nolist spell
  autocmd FileType help               setlocal colorcolumn=
  autocmd FileType markdown,text,todo setlocal colorcolumn=79 textwidth=78
  autocmd FileType python             setlocal expandtab shiftwidth=4 softtabstop=4

  autocmd BufWritePost ~/.vimrc source %
augroup END

