#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

# Description: This script turns off Wi-Fi if the time is between 02:00-16:00.
# F to you procrastination. I run this script automatically every 5 minutes.

# Usage: antipro

TIME=$(date "+%H%M")

if [[ $TIME == <0200-1600> ]]; then
  networksetup -setairportpower en0 off
else
  [ ! -f ~/.wifi ] && networksetup -setairportpower en0 on
fi

