#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

# Description: This script 

# Usage: antipro

TIME=$(date "+%H%M")

if [[ $TIME == <0200-1600> ]]; then
  networksetup -setairportpower en0 off
else
  networksetup -setairportpower en0 on
fi

