#!/usr/bin/env zsh

# Original by Zach Holman <https://github.com/holman/dotfiles/blob/master/bin/backup>.
# Modified by Göran Gustafsson <gustafsson.g@gmail.com>.

DEVICE_NAME=Keychain
ENCRYPTED_IMAGE=/Volumes/Keychain/Backup.sparseimage
BACKUP_DESTINATION=/Volumes/Backup

DIRECTORIES=(
  Development
  Documents
  Dropbox
  Library
  Movies/Personal
  Music/GBS
  Music/NSFe
  Music/Ringtones
  Pictures
  School
  Sites
  Storage
  "Web Archives"
  YouTube
)

if [ ! -f $ENCRYPTED_IMAGE ]; then
  echo "File $ENCRYPTED_IMAGE doesn't exist!"
  return 1
fi

hdiutil attach -noverify $ENCRYPTED_IMAGE

if [ ! -d $BACKUP_DESTINATION ]; then
  echo "Directory $BACKUP_DESTINATION doesn't exist!"
  return 1
fi

for DIRECTORY in $DIRECTORIES; do
  echo
  rsync -ah --progress --delete --exclude=Library/Caches ~/$DIRECTORY $BACKUP_DESTINATION
done

echo
rsync -ah --progress --delete --exclude=.Trash ~/.* $BACKUP_DESTINATION

hdiutil detach $BACKUP_DESTINATION
diskutil eject $DEVICE_NAME

