#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

# Description: This script deletes various space hogging files/directories.

# Usage: frees

echo "Deleting useless files:"

rm -rfv /Library/Caches/Homebrew
rm -rfv ~/Library/Caches/com.apple.dt.Xcode/Downloads
rm -rfv ~/Library/iTunes/iPhone\ Software\ Updates

