#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

echo "Deleting useless files:"

rm -rfv ~/Library/Caches/com.apple.dt.Xcode/Downloads
rm -rfv ~/Library/iTunes/iPhone\ Software\ Updates

