#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

# Description: This script executes several things i don't want to do manually
# every time i get home.

# Usage: home

open -a Adium
open -a Mail
open -a Reeder
open -a Transmission

