#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

# Description: This script executes a bunch of commands i run twice every week
# to back things up and keep things up-to-date.

# Usage: wedsun

echo -n "Everything plugged in and ready to go? [y/n] "
read ANSWER

if [[ $ANSWER == (y|yes) ]]; then
  echo
  offlineimap
  echo
  brew update
  brew upgrade
  brew cleanup
  echo
  gem update --system
  gem update
  echo
  gemfix
  echo
  otherd
  echo
  vimp
  echo
  webf
  echo "Press Enter when done with webf."
  read
  echo
  frees
  echo
  backup

  open -a Xcode
  open -a "App Store"
else
  echo "\nBye bye!"
fi
