#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

if [[ $# -gt 0 ]]; then
  for ARGUMENT in $*; do
    man -t $ARGUMENT | open -f -a Preview
  done
else
  echo "Usage: $0:t [MAN PAGE(S)]..."
fi

