#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

# Description: This script executes several things i don't want to do manually
# every time i'm going to school.

# Usage: school

osascript -e 'tell application "Adium" to quit'
osascript -e 'tell application "Mail" to quit'
osascript -e 'tell application "Reeder" to quit'
osascript -e 'tell application "Transmission" to quit'

osascript -e 'tell application "Finder" to eject (every disk whose ejectable is true)'
