#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

# Description: This script makes it easy to connect to SMB/CIFS network file
# shares.

# Usage: smb <ip/dns>

if [[ $# == 1 ]]; then
  open "smb://$1"
else
  echo "Usage: $0:t [IP/DNS]..."
fi
