#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

if [[ $UID == 0 ]]; then
  /Applications/MacVim.app/Contents/MacOS/Vim $*
elif [[ $# -gt 0 ]]; then
  /Applications/MacVim.app/Contents/MacOS/Vim -g --remote-tab-silent $*
else
  /Applications/MacVim.app/Contents/MacOS/Vim -g
fi

