#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

ENCRYPTED_IMAGE=/Volumes/Keychain/Backup.sparseimage

if [ -f $ENCRYPTED_IMAGE ]; then
  backup && echo
else
  echo "File $ENCRYPTED_IMAGE does not exist!"
  return 1
fi

offlineimap  && echo
brew update  && echo
brew upgrade && echo
brew cleanup && echo
gem update   && echo
otherd       && echo
vimp         && echo
webf         && echo
frees

open -a Xcode
open -a "App Store"

