#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

backup
echo
offlineimap
echo
brew update && brew upgrade
echo
gem update
echo
otherd
echo
vimp
echo
webf

terminal-notifier -group wedsun -title wedsun -message "Backup and updating almost finished."

echo -n "\nLaunch App Store and Xcode? [y/n] "
read ANSWER

if [[ $ANSWER == yes ]] || [[ $ANSWER == y ]]; then
  open -a "App Store"
  open -a Xcode
fi

terminal-notifier -remove wedsun

