#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

backup
echo
offlineimap
echo
brew update && brew upgrade
echo
brew cleanup
echo
gem update
echo
otherd
echo
vimp
echo
webf

open -a Xcode

