#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

# Fix the permissions on the devices that is needed for Wireshark on OS X.

if ! [ -w /dev/bpf1 ]; then
  sudo chgrp Twiggy /dev/bpf*
  sudo chmod 660 /dev/bpf*
fi

exec $*

