#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

# This modifies the group owner and file permissions on the /dev/bpf* files so
# i can run Wireshark under OS X.

# I have this in my zshrc file to make things work smoothly.
#
# WIRESHARK=(/usr/local/Cellar/wireshark/*/bin/*(N:t))
# for X in $WIRESHARK; do
#   alias $X="wiresharkfix $X"
# done

if [ ! -w /dev/bpf1 ]; then
  sudo chgrp wireshark /dev/bpf*
  sudo chmod 660 /dev/bpf*
fi

exec $*

