#!/usr/bin/env zsh

# Description: Backs up miscellaneous files/directories to server with Rsync.
#
# Usage: backup2srv
#
# Author: Göran Gustafsson (gustafsson.g at gmail.com)
# License: BSD 3-Clause

server=ubuntu-tv1
destination=/media/external

backup_objects=(
  ~/Music/FLAC
  ~/Music/MP3
  /Volumes/External\ 1/Movies
  /Volumes/External\ 1/Series
)

echo -n "SSH test connection to server '${server}'..."
if ! ssh -o ConnectTimeout=10 -q $server exit; then
  echo " Failed! Exiting..."
  exit 1
fi
echo " OK!\n"

echo "Backing up to server '${server}'."

for object in $backup_objects; do
  if [[ -a $object ]]; then
    print -P "\n%B%F{green}Backing up: ${object/${HOME}/~}%f%b"
    rsync --archive --chmod=D755,F644 --human-readable --progress --verbose \
      $object -e ssh ${server}:$destination
  else
    echo "\nObject '${object}' not found! Skipping..."
  fi
done
