#!/usr/bin/env zsh

# Description: This script backs up directories/files to server with rsync.
#
# Usage: backup2srv
#
# Written by Göran Gustafsson (gustafsson.g at gmail.com).
# License: BSD 3-Clause.

server=hoth
destination=/media/external

backup_objects=(
  ~/Music/FLAC
  ~/Music/MP3
)

if ! ssh -o ConnectTimeout=10 -q $server exit; then
  echo "SSH test connection to server '${server}' failed! Exiting..."
  exit 1
fi

echo "Backing up to server '${server}'."

for object in $backup_objects; do
  if [[ -a $object ]]; then
    print -P "\n%B%F{green}Backing up: ${object/${HOME}/~}%f%b"
    rsync --archive --chmod=D755,F644 --delete --human-readable --progress \
      $object -e ssh ${server}:$destination
  else
    echo "\nObject '${object}' not found! Exiting..."
    exit 1
  fi
done
