#!/usr/bin/env zsh

# Description: Syncs miscellaneous files/directories to server with Rsync.
#
# Usage: ext2srv
#
# Author: Göran Gustafsson (gustafsson.g at gmail.com)
# License: BSD 3-Clause

server=ubuntu-tv1
destination=/media/external

sync_objects=(
  /Volumes/External\ 1/Movies
  /Volumes/External\ 1/Series
)

echo -n "SSH test connection to server '${server}'..."
if ! ssh -o ConnectTimeout=10 -q $server exit; then
  echo " Failed! Exiting..."
  exit 1
fi
echo " OK!\n"

echo "Syncing data to server '${server}'."

for object in $sync_objects; do
  if [[ -a $object ]]; then
    print -P "\n%F{green}Syncing: ${object/${HOME}/~}%f"
    rsync --archive --chmod=D755,F644 --delete --human-readable --progress \
      $object -e ssh ${server}:$destination
  else
    echo "\nObject '${object}' not found! Exiting..."
    exit 1
  fi
done
