#!/usr/bin/env zsh

# Description: This script executes a bunch of commands I run frequently to
# back things up and keep things up-to-date.
#
# Dependencies: confirm
#
# Usage: maint
#
# Written by Göran Gustafsson (gustafsson.g at gmail.com).
# License: BSD 3-Clause.

confirm || exit 1

brew update
brew upgrade
brew cleanup
echo
maint-vim
echo
rmhogs
echo
backup
echo
backup2srv
