#!/usr/bin/env zsh

# Description: Executes a bunch of maintenance commands I run regularly.
#
# Usage: maint
#
# Creator: Göran Gustafsson (gustafsson.g at gmail.com)
# License: BSD 3-Clause

if [[ $HOST == Onett ]]; then
  ansible_playbook=setup_macos_home.yml
  backup_toggle=on
elif [[ $HOST == Twoson ]]; then
  ansible_playbook=setup_macos_work.yml
  backup_toggle=off
else
  # TODO: Remove after legacy decom.
  ansible_playbook=setup_macos_home_legacy.yml
  backup_toggle=on
fi

selections=$(dialog \
  --default-button "Cancel" \
  --checklist "Select maintenance commands:" 0 0 0 \
  1 "ansible-playbook $ansible_playbook" on \
  2 "rmhogs" on \
  3 "backup" $backup_toggle \
  4 "backup2srv" $backup_toggle 2>&1 > /dev/tty)

clear

for selection in ${(z)selections}; do
  case $selection in
    1)
      echo
      cd ~/Projects/Ansible
      git pull
      echo
      ansible-playbook $ansible_playbook --ask-become
      cd -
      ;;
    2)
      echo
      rmhogs
      ;;
    3)
      echo
      backup --yes
      ;;
    4)
      echo
      backup2srv
      ;;
  esac
done
