#!/usr/bin/env zsh

# Description: Executes Ansible playbook for local setup.
#
# Usage: maint-ansible
#
# Author: Göran Gustafsson (gustafsson.g at gmail.com)
# License: BSD 3-Clause

case $HOST in
  Onett)
    playbook=setup_macos_home.yml
    ;;
  Twoson)
    git_pull=1
    playbook=setup_macos_work.yml
    ;;
  *)
    echo "Could not determine which Ansible playbook to use! Exiting..."
    exit 1
esac

directory=~/Projects/Ansiblebot

if [[ $git_pull -eq 1 ]]; then
  print -P "%B%F{cyan}git pull @ ${directory/${HOME}/~}:%f%b"
  git -C $directory pull
  echo
fi

print -P "%B%F{cyan}ansible-playbook ${playbook}:%f%b"
confirm || exit 1
cd $directory
ansible-playbook $playbook --ask-become || exit $?
