#!/usr/bin/env zsh

# Description: Converts man pages to PDF files with Preview.app.
#
# Usage: man2pdf <man>
#        man2pdf <man> <man> ...
#
# Author: Göran Gustafsson (gustafsson.g at gmail.com)
# License: BSD 3-Clause

if [[ $# -eq 0 ]]; then
  echo "Usage: ${0:t} [MAN PAGE(S)]..."
  exit
fi

for arg; do
  man -t $arg | open -f -a Preview
done
