#!/usr/bin/env zsh

# Description: Display notification in macOS.
#
# Usage: notify <title> <message>
#
# Author: Göran Gustafsson (gustafsson.g at gmail.com)
# License: BSD 3-Clause

if [[ $# -ne 2 ]]; then
  echo "Usage: ${0:t} [TITLE]... [MESSAGE]..."
  exit
fi

osascript -e "display notification \"$2\" with title \"$1\" sound name \"Glass\""
