#!/usr/bin/env zsh

# Description: This script deletes various space hogging files/directories.
#
# Usage: rmhogs
#
# Creator: Göran Gustafsson (gustafsson.g at gmail.com)
# License: BSD 3-Clause

remove_objects=(
  ~/Library/Caches/Homebrew
  ~/Library/Caches/com.apple.dt.Xcode/Downloads
  ~/Library/Logs/Homebrew
  ~/Library/Mail\ Downloads
  ~/Library/iTunes/iPad\ Software\ Updates
  ~/Library/iTunes/iPhone\ Software\ Updates
)

echo "Deleting space hogging files."

for object in $remove_objects; do
  if [[ -a $object ]]; then
    echo
    rm -rfv $object
  fi
done
