#!/usr/bin/env zsh

# Description: Deletes various space hogging files/directories and unused
# Docker container images.
#
# Usage: rmhogs
#
# Author: Göran Gustafsson (gustafsson.g at gmail.com)
# License: BSD 3-Clause

remove_objects=(
  ~/Library/Caches/Homebrew
  ~/Library/Caches/com.apple.dt.Xcode/Downloads
  ~/Library/Logs/Homebrew
  ~/Library/Mail\ Downloads
  ~/Library/iTunes/iPad\ Software\ Updates
  ~/Library/iTunes/iPhone\ Software\ Updates
)

echo "Removing space hogging files..."

for object in $remove_objects; do
  if [[ -a $object ]]; then
    echo
    rm -rfv $object
  fi
done

echo "\nRemoving dangling Docker images...\n"
docker image prune --force
