#!/usr/bin/env zsh

# Description: This script configures a macOS system the way I like.
#
# Usage: setup-macos
#
# Creator: Göran Gustafsson (gustafsson.g at gmail.com)
# License: BSD 3-Clause

sudo test
if [[ $? -eq 1 ]]; then
  echo "User is not allowed to use sudo! Exiting..."
  exit 1
fi

# Check write permission for homebrew (SIP blocking?).
mkdir -p /usr/local/perm_test
if [[ $? -eq 1 ]]; then
  echo "User is not allowed to write to /usr/local! Exiting..."
  exit 1
else
  rm -rf /usr/local/perm_test
fi

if [[ ! -d /Applications/Xcode.app ]]; then
  echo "Install Xcode first! Exiting..."
  exit 1
fi

chflags hidden ~/Public
chflags nohidden ~/Library

xcode-select --install
echo -n "Press 'Return' when Command Line Tools are installed..."
read -s wait_for_input
echo

git clone https://github.com/Homebrew/brew.git ~/Downloads/homebrew
sudo mv ~/Downloads/homebrew/{*,.*} /usr/local/

/usr/local/bin/brew tap homebrew/cask

/usr/local/bin/brew install \
  ansible \
  ansible-lint \
  bash \
  coreutils \
  cuetools \
  curl \
  ffmpeg \
  flac \
  flake8 \
  git \
  golang \
  grep \
  html2text \
  imagemagick \
  lame \
  less \
  links \
  nmap \
  openssh \
  pylint \
  python \
  renameutils \
  rsync \
  ruby \
  shellcheck \
  shntool \
  svtplay-dl \
  tidy-html5 \
  tmux \
  tree \
  vim \
  wget \
  yamllint \
  youtube-dl \
  zsh

/usr/local/bin/brew install --cask --appdir=~/Applications \
  1password \
  docker \
  dropbox \
  google-chrome \
  hammerspoon \
  handbrake \
  openemu \
  tor-browser \
  transmission \
  visual-studio-code \
  vlc

echo "/usr/local/bin/zsh" | sudo tee -a /etc/shells

ln -s /usr/local/bin/{g,}grep
ln -s /usr/local/bin/{g,}ls

mkdir -p ~/.vim/pack/others/start

ln -s ~/Projects/Dot-Files/Scripts ~/
ln -s ~/Projects/Dot-Files/gitconfig ~/.gitconfig
ln -s ~/Projects/Dot-Files/gitignore_global ~/.gitignore_global
ln -s ~/Projects/Dot-Files/hammerspoon ~/.hammerspoon
ln -s ~/Projects/Dot-Files/timrc ~/.timrc
ln -s ~/Projects/Dot-Files/vim/after ~/.vim/after
ln -s ~/Projects/Dot-Files/vim/templates ~/.vim/templates
ln -s ~/Projects/Dot-Files/vimrc ~/.vimrc
ln -s ~/Projects/Dot-Files/zshenv ~/.zshenv
ln -s ~/Projects/Dot-Files/zshrc ~/.zshrc
ln -s ~/Projects/Tim/tim ~/Scripts/

echo
~/Scripts/maint-vim
