#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

ANSWER=$(echo -e "evince\ngeeqie\ngimp\ngparted\nthunderbird\ntransmission\nwireshark" | dmenu -l 20 -fn '-*-terminus-medium-r-*-*-14-*-*-*-*-*-*')

case $ANSWER in
  evince)       evince           ;;
  geeqie)       geeqie           ;;
  gimp)         gimp             ;;
  gparted)      sudo gparted     ;;
  thunderbird)  thunderbird      ;;
  transmission) transmission-gtk ;;
  wireshark)    wireshark        ;;
esac

