#!/usr/bin/env zsh

# Description: Pretty prints ANSI escape sequence of first 16 terminal colors.
#
# Usage: 16colors
#
# Author: Göran Gustafsson (gustafsson.g at gmail.com)
# License: BSD 3-Clause

for number in {30..37}; do
  echo -n "\033[0;${number}m0;${number}m\033[0m "
done && echo

for number in {30..37}; do
  echo -n "\033[1;${number}m1;${number}m\033[0m "
done && echo

for number in {40..47}; do
  echo -n "\033[1;${number}m1;${number}m\033[0m "
done && echo
