#!/usr/bin/env zsh

# Description: This script prints out 256 different colors that can be used in
# the terminal. Handy when making color schemes for Vim.
#
# Usage: 256colors
#
# Written by Göran Gustafsson (gustafsson.g at gmail.com).
# License: BSD 3-Clause.

reset="\x1b[0m"

for number in {0..255}; do
  foreground="\x1b[38;5;${number}m"
  background="\x1b[48;5;${number}m"

  echo "$background    $reset ${foreground}Color ${number}$reset"
done
