#!/usr/bin/env zsh

# Description: This script prints out 256 different colors that can be used in
# the terminal. Handy when making color schemes for Vim.
#
# Usage: 256colors
#
# Written by Göran Gustafsson (gustafsson.g at gmail.com).
# License: BSD 3-Clause.

for number in {0..255}; do
  echo "\x1b[38;5;${number}mColor $number"
done
