#!/usr/bin/env zsh

# Description: Pretty prints all 256 terminal colors. Handy when making color
# schemes for Vim etc.
#
# Usage: 256colors
#
# Author: Göran Gustafsson (gustafsson.g at gmail.com)
# License: BSD 3-Clause

reset="\x1b[0m"

for number in {0..255}; do
  foreground="\x1b[38;5;${number}m"
  background="\x1b[48;5;${number}m"

  echo "$background    $reset ${foreground}Color ${number}$reset"
done
