#!/usr/bin/env ruby

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

# Description: Print out the date that is X days from now. Minus works too.

# Usage: ahead <days>

unless ARGV.length == 1
  puts "Usage: #{File.basename($0)} [DAYS]..."
  exit
end

require "date"

begin
  days = Integer(ARGV[0])
rescue
  abort "Invalid argument!"
end

date = Date.today + days
weekday = date.strftime("%A")

puts "#{date} - #{weekday}"
