#!/usr/bin/env zsh

# Description: This script displays the 20 biggest files/directories inside a
# directory.
#
# Usage: bigf
#        bigf <path>
#
# Written by Göran Gustafsson (gustafsson.g at gmail.com).
# License: BSD 3-Clause.

if [[ $# -eq 0 ]]; then
  du -sk * | sort --numeric-sort --reverse | head -n 20
elif [[ $# -eq 1 ]]; then
  if [[ -d $1 ]]; then
    cd $1
    du -sk * | sort --numeric-sort --reverse | head -n 20
  else
    echo "Path '${1}' is not a directory! Exiting..."
    exit 1
  fi
else
  echo "Usage: ${0:t} [PATH]..."
fi
