#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

# Description: This script displays the 20 biggest files/directories inside a
# directory.

# Usage: bigf
#        bigf <path>

if [[ $# -eq 0 ]]; then
  du -sk * | sort --numeric-sort --reverse | head -n 20
elif [[ $# -eq 1 ]]; then
  if [[ -d $1 ]]; then
    du -sk ${1}/* | sort --numeric-sort --reverse | head -n 20
  else
    echo "Path '${1}' is not a directory! Exiting..."
    exit 1
  fi
else
  echo "Usage: ${0:t} [PATH]..."
fi
