#!/usr/bin/env zsh

# Description: Like "cd .." but on steroids. If argument is supplied then
# current directory is changed to closest directory matching pattern.
#
# Example:
#
#   /Users/GLEG/Development/Python $ cdb Us
#   /Users $
#
# ~/.zshrc:
#
#   alias cdb="source cdb"
#
# Usage: cdb
#        cdb <pattern>
#
# Original script: https://github.com/vigneshwaranr/bd/blob/master/bd
# Modified by: Göran Gustafsson (gustafsson.g at gmail.com)

if [[ $# -eq 1 ]]; then
  cdb_dir=$(echo $PWD | sed 's|\(.*/'${1}'[^/]*/\).*|\1|')
  if [[ $cdb_dir != $PWD ]]; then
    cd "$cdb_dir"
  else
    echo "No match found!"
  fi
  unset cdb_dir
elif [[ $# -eq 0 ]]; then
  cd ..
else
  echo "Usage: ${0:t} [PATTERN]..."
fi
