#!/usr/bin/env zsh

# Description: Select bookmark with Fzf and go to directory. Bookmarks are
# symbolic links in ~/.config/nnn/bookmarks, or ~/.bookmarks as fallback.
#
# ~/.zshrc:
#
#   alias cdj="source cdj"
#
# Usage: cdj
#
# Author: Göran Gustafsson (gustafsson.g at gmail.com)
# License: BSD 3-Clause

cdj_nnn=${XDG_CONFIG_HOME:-$HOME/.config}/nnn/bookmarks
if [[ -d $cdj_nnn ]]; then
  cdj_dir=$cdj_nnn
elif [[ -d ~/.bookmarks ]]; then
  cdj_dir=~/.bookmarks
else
  echo "Failed to find bookmarks directory! Exiting..."
  return 1
fi

cdj_sel=$(\ls "$cdj_dir" | fzf --tac)
if [[ -z $cdj_sel ]]; then
  echo "Nothing selected! Exiting..."
  return 1
fi

cdj_dst=$(readlink "${cdj_dir}/$cdj_sel") # Destination of symbolic link.
echo $cdj_dst
cd "$cdj_dst"

# Be nice and clean up before leaving...
unset cdj_dir cdj_dst cdj_nnn cdj_sel
