#!/usr/bin/env zsh

# Description: Frontend for https://cheat.sh. Result is displayed in Nvim pager
# with custom cheat filetype for highlights. Flag --ask starts interactive mode
# for use in Tmux popup window.
#
# ~/.config/nvim/syntax/cheat.vim:
#
#   syntax match Comment /^#.*/
#
# ~/.tmux.conf:
#
#   bind Enter menu -T "#[align=centre] Launcher " \
#     "Open Cheat" c "popup -EE -h 60% -w 60% cheat --ask"
#
# Usage: cheat
#        cheat <query>
#        cheat --ask
#
# Author: Göran Gustafsson (gustafsson.g at gmail.com)
# License: BSD 3-Clause

url=https://cheat.sh

# Command "view" is basically "nvim -R", see separate script.
pager="view -c 'setlocal filetype=cheat nolist' -"

if [[ $# -ge 1 ]]; then
  if [[ $1 == (a-|--ask) ]]; then
    topic=$(dialog --inputbox "Enter cheat.sh topic..." 0 40 2>&1 > /dev/tty)
    clear
  else
    topic=$*
  fi

  # Replace spaces with + that is needed in the URL.
  query=${topic/ /+}

  # Fetch cheat page and fix some formatting issues.
  # Remove empty lines at start and end: /./,$!d
  # Append two empty lines before each header: s/#\[X/\n\n## \[X/g
  # Replace multiple empty lines with one: /^$/N;/^\n$/D
  response=$(curl --no-progress-meter "${url}/${query}?T" | \
    sed -e '/^$/N;/^\n$/D' \
        -e 's/#\[cheat/\n\n## \[cheat/g' \
        -e 's/#\[tldr/\n\n## \[tldr/g' | \
    sed -e '/./,$!d')

  output="${output}$response"

  echo $output | eval $pager
else
  curl --no-progress-meter "${url}/:help"
fi
