#!/usr/bin/env zsh

# Description: Frontend for https://cheat.sh. Result is displayed in Nvim pager
# with custom cheat filetype for highlights.
#
# ~/.config/nvim/syntax/cheat.vim:
#
#   syntax match Comment /^#.*/
#
# Usage: cheat
#        cheat <query>
#
# Author: Göran Gustafsson (gustafsson.g at gmail.com)
# License: BSD 3-Clause

url=https://cheat.sh
pager="nvim -R -c 'setlocal filetype=cheat nolist | nmap q <Cmd>q<CR>' -"

if [[ $# -ge 1 ]]; then
  # Replace spaces with + that is needed in the URL.
  query=${*/ /+}

  # Fetch cheat page and fix some formatting issues.
  # Remove empty lines at start and end: /./,$!d
  # Append two empty lines before each header: s/#\[X/\n\n## \[X/g
  # Replace multiple empty lines with one: /^$/N;/^\n$/D
  response=$(curl --no-progress-meter "${url}/${query}?T" | \
    sed -e '/^$/N;/^\n$/D' \
        -e 's/#\[cheat/\n\n## \[cheat/g' \
        -e 's/#\[tldr/\n\n## \[tldr/g' | \
    sed -e '/./,$!d')

  output="${output}$response"

  echo $output | eval $pager
else
  curl --no-progress-meter "${url}/:help"
fi
