#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

# Description: This script checks the git status of all my projects.

# Usage: chkp

for DIRECTORY in ~/Projects/*; do
  cd $DIRECTORY

  if [[ -n $(git rev-list origin..HEAD 2> /dev/null) ]]; then
    print -P "%B%F{cyan}$DIRECTORY:t:%f%b"
    git status --branch --short
    echo
  elif [[ -n $(git status --short 2> /dev/null) ]]; then
    print -P "%B%F{red}$DIRECTORY:t:%f%b"
    git status --branch --short
    echo
  elif [[ -d .git ]]; then
    CLEAN_REPOS+=($DIRECTORY:t)
  else
    NOT_REPOS+=($DIRECTORY:t)
  fi
done

if [[ ${#CLEAN_REPOS} -gt 0 ]]; then
  print -P "%B%F{green}Clean repo(s):%f%b"
  for REPO in $CLEAN_REPOS; do
    echo " * $REPO"
  done
fi

[[ ${#CLEAN_REPOS} -gt 0 && ${#NOT_REPOS} -gt 0 ]] && echo

if [[ ${#NOT_REPOS} -gt 0 ]]; then
  print -P "%B%F{blue}Not Git repo(s):%f%b"
  for NAME in $NOT_REPOS; do
    echo " * $NAME"
  done
fi
