#!/usr/bin/env zsh

# Description: An extremely simple frontend for https://cheat.sh.
#
# Usage: cht
#        cht <query>
#
# Written by Göran Gustafsson (gustafsson.g at gmail.com).
# License: BSD 3-Clause.

url="https://cheat.sh"
pager="less" # pager="view -c 'setlocal colorcolumn= nolist' -"

if [[ $# -ge 1 ]]; then
  # Replace spaces with + that is needed in the URL.
  query="${*/ /+}?T"

  # Fetch page and replace multiple empty lines with only one.
  response=$(curl --no-progress-meter "${url}/$query" | sed '/^$/N;/^\n$/D')

  echo "# ${url}/${query}\n\n$response" | eval $pager
else
  curl --no-progress-meter "${url}/:help"
fi
