#!/usr/bin/env zsh

# Description: Opens temporary file in $VISUAL and copies content to system
# clipboard afterwards. Preferably executed through system wide key binding or
# in Tmux "display-popup" window.
#   __
#  /  \
#  |  |      .------------------.
#  @  @      | It looks like    |
#  || ||     | you would rather |
#  || ||  <--| use a real       |
#  |\_/|     | text editor!     |
#  \___/     '------------------'
#
# Usage: clippy
#
# Author: Göran Gustafsson (gustafsson.g at gmail.com)
# License: BSD 3-Clause

if whence -p pbcopy &> /dev/null; then
  copy_cmd=pbcopy
elif whence -p xsel &> /dev/null; then
  copy_cmd=xsel
else
  echo "Failed to find clipboard command! Exiting..."
  exit 1
fi

tmp_file=$(mktemp)
eval ${VISUAL:=nvim} $tmp_file

if [[ $? -eq 0 && -s $tmp_file ]]; then
  content=$(cat $tmp_file)
  echo -n $content | eval $copy_cmd
fi
