#!/usr/bin/env zsh

# Description: Asks for confirmation to proceed. Exits with status 0 (success)
# or status 1 (error) depending on answer. Anything but input of "y" or "Y"
# leads to exit status 1.
#
# Usage: confirm && x
#        confirm || exit 1
#
# Author: Göran Gustafsson (gustafsson.g at gmail.com)
# License: BSD 3-Clause

read -q "REPLY?Are you sure you want to proceed? [y/n] "
echo

if [[ $REPLY == (y|Y) ]]; then
  echo
  exit 0
fi

exit 1
