#!/usr/bin/env ruby

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

# Description: This script reads the file ~/.countdowns and calculates the
# remaining days until the specific date on each entry in the file.
#
# An entry in the file looks like this:
#
# "Title here", 2017-01-14

# Usage: countd

require "csv"

csv_file = "#{Dir.home}/.countdowns"

if !File.exist?(csv_file)
  abort "File '#{csv_file}' does not exist!"
elsif CSV.read(csv_file).length < 1
  abort "No entries found!"
end

CSV.foreach(csv_file) do |row|
  puts if $. > 1

  unless row.size == 2
    puts "The row on line #{$.} is not 2 columns. Skipping!"
    next
  end

  title = row[0]
  date = row[1].strip!

  begin
    future = Date.parse(date)
  rescue
    puts "Invalid date on line #{$.}. Skipping!"
    next
  end

  days_left = (future - Date.today).to_i
  puts "#{title}\n#{days_left} day(s) left until #{date}"
end
