#!/usr/bin/env ruby

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

# Description: This script reads the file ~/.countdowns and calculates the
# remaining days until the specific date on each entry in the file.
#
# An entry in the file looks like this:
#
# "Title here", 2017-01-14

# Usage: countd

require "csv"

file = "#{Dir.home}/.countdowns"
today = Date.today
position = 0

if !File.exist?(file)
  abort "File '~/.countdowns' not found!"
elsif CSV.read(file).length == 0
  abort "No entries found!"
end

CSV.foreach(file) do |row|
  if row.size != 2
    puts if position > 0
    puts "The row on line #{position + 1} is not 2 columns. Skipping!"
    position += 1

    next
  end

  title = row[0]
  date = row[1].strip!

  begin
    future = Date.parse(date)
  rescue
    next
  end

  days_left = (future - today).to_i

  puts if position > 0
  puts "#{title}\n#{days_left} day(s) left until #{date}"

  position += 1
end
