#!/usr/bin/env ruby

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

# Description: This script reads the file ~/.countdowns and calculates the
# remaining days until the specific date on each entry in the file.
#
# An entry in the file looks like this:
#
# 2017-01-14,"Title here"

# Usage: countd

require "csv"

csv_file = "#{Dir.home}/.countdowns"

if !File.exist?(csv_file)
  abort "File '#{csv_file}' does not exist! Exiting..."
elsif CSV.read(csv_file).empty?
  abort "No entries found! Exiting..."
end

CSV.foreach(csv_file) do |row|
  # Print empty line unless the current line in the CSV file is the first one.
  # Using this empty line as a separator between every entry/error message.
  puts unless $. == 1

  unless row.size == 2
    puts "The row on line #{$.} is not 2 columns. Skipping!"
    next
  end

  date = row[0]
  title = row[1]

  begin
    future = Date.parse(date)
  rescue
    puts "Invalid date on line #{$.}. Skipping!"
    next
  end

  days_left = (future - Date.today).to_i
  puts "#{title}\n#{days_left} day(s) left until #{date}"
end
