#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

# Description: This script counts the number of files inside a directory.

# Usage: countf
#        countf <path>

if [[ $# -eq 0 ]]; then
  ls -1 | wc -l
elif [[ $# -eq 1 ]]; then
  ls -1 $1 | wc -l
else
  echo "Usage: ${0:t} [PATH]..."
fi
