#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

# Description: This script automatically downloads several miscellaneous git
# repositories i want to keep up-to-date.

# Usage: dl_misc

function headline {
  print -P "%B%F{cyan}Checking for $* updates.%f%b"
}

if [[ -d ~/Development/Hello\ World ]]; then
  headline "Hello World"
  cd ~/Development/Hello\ World
  git pull
else
  git clone git://github.com/leachim6/hello-world.git ~/Development/Hello\ World
fi

echo

if [[ -d ~/Documents/Reading/Dive\ Into\ HTML5 ]]; then
  headline "Dive Into HTML5"
  cd ~/Documents/Reading/Dive\ Into\ HTML5
  git pull
else
  git clone git://github.com/diveintomark/diveintohtml5.git ~/Documents/Reading/Dive\ Into\ HTML5
fi

echo

if [[ -d ~/Projects/Tim\ Fork ]]; then
  headline "Tim (hdonnay fork)"
  cd ~/Projects/Tim\ Fork
  git pull
else
  git clone git://github.com/hdonnay/Tim.git ~/Projects/Tim\ Fork
fi

echo

if [[ -d ~/Storage/Fonts/Blackout ]]; then
  headline "Blackout"
  cd ~/Storage/Fonts/Blackout
  git pull
else
  git clone git://github.com/theleagueof/blackout.git ~/Storage/Fonts/Blackout
fi

echo

if [[ -d ~/Storage/Fonts/Knewave ]]; then
  headline "Knewave"
  cd ~/Storage/Fonts/Knewave
  git pull
else
  git clone git://github.com/theleagueof/knewave.git ~/Storage/Fonts/Knewave
fi

echo

if [[ -d ~/Storage/Fonts/League\ Gothic ]]; then
  headline "League Gothic"
  cd ~/Storage/Fonts/League\ Gothic
  git pull
else
  git clone git://github.com/theleagueof/league-gothic.git ~/Storage/Fonts/League\ Gothic
fi

echo

if [[ -d ~/Storage/Fonts/Orbitron ]]; then
  headline "Orbitron"
  cd ~/Storage/Fonts/Orbitron
  git pull
else
  git clone git://github.com/theleagueof/orbitron.git ~/Storage/Fonts/Orbitron
fi

echo

if [[ -d ~/Storage/Fonts/Ostrich\ Sans ]]; then
  headline "Ostrich Sans"
  cd ~/Storage/Fonts/Ostrich\ Sans
  git pull
else
  git clone git://github.com/theleagueof/ostrich-sans.git ~/Storage/Fonts/Ostrich\ Sans
fi

echo

if [[ -d ~/Storage/Fonts/Prociono ]]; then
  headline "Prociono"
  cd ~/Storage/Fonts/Prociono
  git pull
else
  git clone git://github.com/theleagueof/prociono.git ~/Storage/Fonts/Prociono
fi

echo

if [[ -d ~/Storage/Fonts/Sniglet ]]; then
  headline "Sniglet"
  cd ~/Storage/Fonts/Sniglet
  git pull
else
  git clone git://github.com/theleagueof/sniglet.git ~/Storage/Fonts/Sniglet
fi
