#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

# Description: This script downloads and updates git repositories.

# Usage: dl_misc
#        dl_misc install

if [[ $1 == install ]]; then
  echo "Downloading git repositories!"

  git clone git://github.com/diveintomark/diveintohtml5.git ~/Documents/Reading/Dive\ Into\ HTML5
  git clone git://github.com/hdonnay/Tim.git ~/Projects/Tim\ Fork
  git clone git://github.com/leachim6/hello-world.git ~/Development/Hello\ World
  git clone git://github.com/theleagueof/blackout.git ~/Storage/Fonts/Blackout
  git clone git://github.com/theleagueof/knewave.git ~/Storage/Fonts/Knewave
  git clone git://github.com/theleagueof/league-gothic.git ~/Storage/Fonts/League\ Gothic
  git clone git://github.com/theleagueof/orbitron.git ~/Storage/Fonts/Orbitron
  git clone git://github.com/theleagueof/ostrich-sans.git ~/Storage/Fonts/Ostrich\ Sans
  git clone git://github.com/theleagueof/prociono.git ~/Storage/Fonts/Prociono
  git clone git://github.com/theleagueof/sniglet.git ~/Storage/Fonts/Sniglet
else
  repositories=(
    ~/Development/Hello\ World(N)
    ~/Documents/Reading/Dive\ Into\ HTML5(N)
    ~/Projects/Tim\ Fork(N)
    ~/Storage/Fonts/Blackout(N)
    ~/Storage/Fonts/Knewave(N)
    ~/Storage/Fonts/League\ Gothic(N)
    ~/Storage/Fonts/Orbitron(N)
    ~/Storage/Fonts/Ostrich\ Sans(N)
    ~/Storage/Fonts/Prociono(N)
    ~/Storage/Fonts/Sniglet(N)
  )

  if [[ -z $repositories ]]; then
    echo "No repositories found! Exiting..."
    exit 1
  fi

  echo "Updating all git repositories!"

  for repository in $repositories; do
    if [[ -d $repository ]]; then
      print -P "\n%B%F{cyan}Running git pull in ${repository/$HOME/~}%f%b"
      cd $repository
      git pull
    fi
  done
fi
