#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

# Description: This script automatically downloads several Vim related git
# repositories i want to keep up-to-date.

# Usage: dl_vim

function headline {
  print -P "%B%F{cyan}Checking for $* updates.%f%b"
}

if [[ -d ~/.vim/bundle/gist ]]; then
  headline "Gist"
  cd ~/.vim/bundle/gist
  git pull
else
  git clone git://github.com/mattn/gist-vim.git ~/.vim/bundle/gist
fi

echo

if [[ -d ~/.vim/bundle/gundo ]]; then
  headline "Gundo"
  cd ~/.vim/bundle/gundo
  git pull
else
  git clone git://github.com/sjl/gundo.vim.git ~/.vim/bundle/gundo
fi

echo

if [[ -d ~/.vim/bundle/lusty ]]; then
  headline "Lusty"
  cd ~/.vim/bundle/lusty
  git pull
else
  git clone git://github.com/sjbach/lusty.git ~/.vim/bundle/lusty
fi

echo

if [[ -d ~/.vim/bundle/nerdcommenter ]]; then
  headline "NERDCommenter"
  cd ~/.vim/bundle/nerdcommenter
  git pull
else
  git clone git://github.com/scrooloose/nerdcommenter.git ~/.vim/bundle/nerdcommenter
fi

echo

if [[ -d ~/.vim/bundle/nerdtree ]]; then
  headline "NERDTree"
  cd ~/.vim/bundle/nerdtree
  git pull
else
  git clone git://github.com/scrooloose/nerdtree.git ~/.vim/bundle/nerdtree
fi

echo

if [[ -d ~/.vim/pathogen ]]; then
  headline "Pathogen"
  cd ~/.vim/pathogen
  git pull
else
  git clone git://github.com/tpope/vim-pathogen.git ~/.vim/pathogen
fi

echo

if [[ -d ~/.vim/bundle/repeat ]]; then
  headline "Repeat"
  cd ~/.vim/bundle/repeat
  git pull
else
  git clone git://github.com/tpope/vim-repeat.git ~/.vim/bundle/repeat
fi

echo

if [[ -d ~/.vim/bundle/speeddating ]]; then
  headline "Speeddating"
  cd ~/.vim/bundle/speeddating
  git pull
else
  git clone git://github.com/tpope/vim-speeddating.git ~/.vim/bundle/speeddating
fi

echo

if [[ -d ~/.vim/bundle/surround ]]; then
  headline "Surround"
  cd ~/.vim/bundle/surround
  git pull
else
  git clone git://github.com/tpope/vim-surround.git ~/.vim/bundle/surround
fi

echo

if [[ -d ~/.vim/bundle/webapi ]]; then
  headline "WebAPI"
  cd ~/.vim/bundle/webapi
  git pull
else
  git clone git://github.com/mattn/webapi-vim.git ~/.vim/bundle/webapi
fi
