#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

# Description: This script downloads and updates Vim plugins.

# Usage: dl_vim
#        dl_vim install

if [[ $1 == install ]]; then
  directory=~/.vim/bundle

  echo "Downloading Vim plugins!"

  git clone git://github.com/tpope/vim-pathogen.git ~/.vim/pathogen
  git clone git://github.com/goldfeld/vim-seek.git $directory/vim-seek
  git clone git://github.com/mattn/gist-vim.git $directory/gist-vim
  git clone git://github.com/mattn/webapi-vim.git $directory/webapi-vim
  git clone git://github.com/scrooloose/nerdcommenter.git $directory/nerdcommenter
  git clone git://github.com/scrooloose/nerdtree.git $directory/nerdtree
  git clone git://github.com/sjbach/lusty.git $directory/lusty
  git clone git://github.com/sjl/gundo.vim.git $directory/gundo.vim
  git clone git://github.com/tpope/vim-endwise.git $directory/vim-endwise
  git clone git://github.com/tpope/vim-repeat.git $directory/vim-repeat
  git clone git://github.com/tpope/vim-speeddating.git $directory/vim-speeddating
  git clone git://github.com/tpope/vim-surround.git $directory/vim-surround
else
  plugins=(~/.vim/pathogen(N) ~/.vim/bundle/*(N))

  if [[ -z $plugins ]]; then
    echo "No Vim plugins found! Exiting..."
    exit 1
  fi

  echo "Updating all Vim plugins!"

  for plugin in $plugins; do
    if [[ -d $plugin ]]; then
      print -P "\n%B%F{cyan}Running git pull on: ${plugin:t}%f%b"
      cd $plugin
      git pull
    fi
  done
fi
