#!/usr/bin/env zsh

# Original script created by Vigneshwaran Raveendran:
#   <https://github.com/vigneshwaranr/bd/blob/master/bd>.
# Modified by Göran Gustafsson <gustafsson.g@gmail.com>.

# Description: This script works just like "cd .." if no argument is supplied
# but if an argument is used then $PWD is searched through for a match. If one
# is found then the current directory is changed to the matching directory.
#
# For example if the current directory is "/Users/GLEG/Development/Ruby" and
# the argument "GL" is used then the working directory would be changed to
# "/Users/GLEG" instead. No more "cd ../../.." :)
#
# This script must be used from an alias. I have this in ~/.zshrc:
#
# alias ..="source dotdot"
#
# The source command before the script name must be there to make the script
# run in the current shell.

# Usage: ..
#        .. <pattern>

if [[ $# -gt 1 ]]; then
  echo "Usage: ${0:t} [PATTERN]..."
  exit
fi

if [[ $# -eq 1 ]]; then
  new_pwd=$(echo $PWD | sed 's|\(.*/'${1}'[^/]*/\).*|\1|')

  if [[ $PWD != $new_pwd ]]; then
    cd $new_pwd
  else
    echo "No result found!"
  fi
else
  cd ..
fi
