#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

# Description: This script creates symlinks, directories etc

# Usage: dotfiles

if [[ $OSTYPE == darwin* ]]; then
  ln -s ~/Projects/Dot\ Files/Scripts ~/Scripts
else
  git clone git@github.com:ggustafsson/IP-Kalkylatorn.git ~/Projects/IP\ Kalkylatorn
  git clone git@github.com:ggustafsson/Ninja-Color-Scheme.git ~/Projects/Ninja\ Color\ Scheme
  git clone git@github.com:ggustafsson/Tim.git ~/Projects/Tim

  ln -s ~/Projects/IP\ Kalkylatorn/ipkalk ~/Scripts/ipkalk
  ln -s ~/Projects/Tim/tim ~/Scripts/tim
fi

ln -s ~/Projects/Dot\ Files/gitconfig ~/.gitconfig
ln -s ~/Projects/Dot\ Files/gitignore_global ~/.gitignore_global
ln -s ~/Projects/Dot\ Files/ssh_config ~/.ssh/config
ln -s ~/Projects/Dot\ Files/timrc ~/.timrc
ln -s ~/Projects/Dot\ Files/tmux.conf ~/.tmux.conf
ln -s ~/Projects/Dot\ Files/vimrc ~/.vimrc
ln -s ~/Projects/Dot\ Files/zshenv ~/.zshenv
ln -s ~/Projects/Dot\ Files/zshrc ~/.zshrc

mkdir ~/.vim
mkdir ~/.vim/autoload
mkdir ~/.vim/backups
mkdir ~/.vim/bundle
mkdir ~/.vim/colors
mkdir ~/.vim/undos

ln -s ~/Projects/Dot\ Files/vim/snippets ~/.vim/
ln -s ~/Projects/Dot\ Files/vim/syntax ~/.vim/

~/Scripts/vimp

ln -s ~/.vim/pathogen/autoload/pathogen.vim ~/.vim/autoload/
ln -s ~/Projects/Ninja\ Color\ Scheme/colors/ninja.vim ~/.vim/colors/
