#!/usr/bin/env zsh

# Description: This script installs/updates Go packages.
#
# Usage: fetch-go
#
# Written by Göran Gustafsson (gustafsson.g at gmail.com).
# License: BSD 3-Clause.

packages=(
  github.com/alecthomas/gometalinter
  github.com/fatih/motion
  github.com/golang/lint/golint
  github.com/josharian/impl
  github.com/jstemmer/gotags
  github.com/kisielk/errcheck
  github.com/klauspost/asmfmt/cmd/asmfmt
  github.com/nsf/gocode
  github.com/rogpeppe/godef
  github.com/zmb3/gogetdoc
  golang.org/x/crypto/ssh/terminal
  golang.org/x/tools/cmd/goimports
  golang.org/x/tools/cmd/gorename
  golang.org/x/tools/cmd/guru
)

for pkg in $packages; do
  echo "Fetching package: $pkg"
  go get -u $pkg
done
