#!/usr/bin/env zsh

# Description: This script downloads/updates Vim plugins.
#
# Usage: fetch-vim
#
# Written by Göran Gustafsson (gustafsson.g at gmail.com).
# License: BSD 3-Clause.

pack_path=~/.vim/pack/others

function fetch {
  dir=${pack_path}/$1
  url=$2

  print -P "\n%B%F{cyan}Fetching plugin: ${dir:t}%f%b"
  if [[ -d $dir ]]; then
    git -C $dir pull
  else
    git clone $url $dir
  fi
}

if [[ ! -d $pack_path ]]; then
  echo "Creating directory: $pack_path"
  mkdir -p $pack_path
  echo
fi

echo "Fetching Vim plugins..."

fetch start/syntastic       https://github.com/vim-syntastic/syntastic.git
fetch start/vim-commentary  https://github.com/tpope/vim-commentary.git
fetch start/vim-endwise     https://github.com/tpope/vim-endwise.git
fetch start/vim-go          https://github.com/fatih/vim-go.git
fetch start/vim-mundo       https://github.com/simnalamburt/vim-mundo.git
fetch start/vim-repeat      https://github.com/tpope/vim-repeat.git
fetch start/vim-speeddating https://github.com/tpope/vim-speeddating.git
fetch start/vim-surround    https://github.com/tpope/vim-surround.git

echo "\nGenerating help tags for all plugins under ~/.vim/pack/*/start"
vim -c "helptags ALL" -c q
