#!/usr/bin/env zsh

# Description: This script downloads/updates Vim plugins.
#
# Usage: fetch-vim
#
# Written by Göran Gustafsson (gustafsson.g at gmail.com).
# License: BSD 3-Clause.

function fetch {
  dir=$1
  url=$2

  print -P "\n%B%F{cyan}Fetching plugin: ${dir:t}%f%b"
  if [[ -d $dir ]]; then
    git -C $dir pull
  else
    git clone $url $dir
  fi
}

echo "Fetching Vim plugins."

mkdir -p ~/.vim/pack/others/start

fetch ~/.vim/pack/others/start/syntastic    https://github.com/vim-syntastic/syntastic.git
fetch ~/.vim/pack/others/start/vim-go       https://github.com/fatih/vim-go.git
fetch ~/.vim/pack/others/start/vim-mundo    https://github.com/simnalamburt/vim-mundo.git
fetch ~/.vim/pack/others/start/vim-surround https://github.com/tpope/vim-surround.git

# Generate help tags for all plugins under ~/.vim/pack/*/start.
vim -u NONE -c "helptags ALL" -c q
