#!/usr/bin/env zsh

# Description: This script downloads/updates Vim plugins.
#
# Usage: fetch_vim
#
# Written by Göran Gustafsson (gustafsson.g at gmail.com).
# License: BSD 3-Clause.

function fetch {
  dir=$1
  url=$2

  print -P "\n%B%F{cyan}Fetching plugin: ${dir:t}%f%b"
  if [[ -d $dir ]]; then
    git -C $dir pull
  else
    git clone $url $dir
  fi
}

echo "Fetching Vim plugins."

mkdir -p ~/.vim/autoload
mkdir -p ~/.vim/bundle

fetch ~/.vim/vim-pathogen https://github.com/tpope/vim-pathogen.git
ln -s ~/.vim/vim-pathogen/autoload/pathogen.vim ~/.vim/autoload/pathogen.vim &> /dev/null

fetch ~/.vim/bundle/gundo.vim       https://github.com/sjl/gundo.vim.git
fetch ~/.vim/bundle/nerdcommenter   https://github.com/scrooloose/nerdcommenter.git
fetch ~/.vim/bundle/nerdtree        https://github.com/scrooloose/nerdtree.git
fetch ~/.vim/bundle/syntastic       https://github.com/scrooloose/syntastic.git
fetch ~/.vim/bundle/vim-endwise     https://github.com/tpope/vim-endwise.git
fetch ~/.vim/bundle/vim-go          https://github.com/fatih/vim-go.git
fetch ~/.vim/bundle/vim-repeat      https://github.com/tpope/vim-repeat.git
fetch ~/.vim/bundle/vim-speeddating https://github.com/tpope/vim-speeddating.git
fetch ~/.vim/bundle/vim-surround    https://github.com/tpope/vim-surround.git
