#!/usr/bin/env zsh

# Description: Perform case insensitive search for files under current working
# directory or path specified through argument.
#
# Usage: findf <pattern>
#        findf <pattern> <path>
#
# Creator: Göran Gustafsson (gustafsson.g at gmail.com)
# License: BSD 3-Clause

if [[ $# -eq 1 ]]; then
  find -L . -iname "*${1}*"
elif [[ $# -eq 2 ]]; then
  find -L "$2" -iname "*${1}*"
else
  echo "Usage: ${0:t} [PATTERN]... [PATH]..."
fi
