#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

# Description: This script performs a case insensitive search for files under
# the current working directory and prints out the relative path to them.

# Usage: findf <pattern>

if [[ ! $# -eq 1 ]]; then
  echo "Usage: ${0:t} [PATTERN]..."
  exit
fi

find -L . -iname $1
