#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

# Description: This script converts FLAC files to high quality MP3 files.

# Usage: flaccon <file>
#        flaccon *.flac
#        find . -type f -iname "*.flac" -exec flaccon "{}" \;

if [[ $# -gt 0 ]]; then
  echo "Converting FLAC file(s) to MP3."

  for FILE in $*; do
    if [[ -f $FILE ]]; then
      if [[ $FILE == *.flac ]]; then
        TAGS=(TITLE ARTIST ALBUM TRACKNUMBER TOTALTRACKS GENRE DATE)

        # Put all tag information inside of various shell variables.
        for TAG in $TAGS; do
          INFO=$(metaflac --show-tag=$TAG $FILE)
          typeset $TAG=${INFO#*=} # Set values for $TITLE, $ARTIST and so on.
        done

        echo

        # Print out all tag information.
        for TAG in $TAGS; do
          echo $TAG=${(P)TAG}
        done

        # Decode FLAC file with "flac" and encode it to MP3 with "lame".
        flac -dc $FILE | lame -b 320 -h --ignore-tag-errors \
          --tt "$TITLE" \
          --ta "$ARTIST" \
          --tl "$ALBUM" \
          --tn "$TRACKNUMBER/$TOTALTRACKS" \
          --tg "$GENRE" \
          --ty "$DATE" \
          --add-id3v2 - "$FILE:r.mp3"
      else
        echo "\nFile '$FILE' does not end with flac."
      fi
    else
      echo "\nFile '$FILE' does not exist."
    fi
  done
else
  echo "Usage: $0:t [FILENAME(S)]..."
fi
