#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

# Description: This script replaces the crappy shebang line that gem adds.

# Usage: gemfix

directory=~/.gem/ruby/bin
suffix=tmp

for file in $directory/*; do
  echo "Replacing the shebang line in file: $file"
  echo '#!/usr/bin/env ruby' > ${file}_$suffix
  tail -n +2 $file >> ${file}_$suffix
  cat ${file}_$suffix > $file
  rm $directory/*_$suffix
done
