#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

# Description: This script creates an animated gif image of several images.

# Usage: gifit <file1> <file2> ...
#        gifit *.jpg

if [[ $# -gt 1 ]]; then
  for FILE in $*; do
    if [[ ! -f $FILE ]]; then
      echo "File '$FILE' does not exist."
      return 1
    fi
  done

  FILENAME=animated_$(date '+%Y-%m-%d_%H%M').gif
  convert -delay 30 -loop 0 $* $FILENAME

  [[ $OSTYPE == darwin* ]] && open -a Safari $FILENAME
else
  echo "Usage: $0:t [FILENAMES]..."
fi
