#!/usr/bin/env zsh

# Description: This script creates an animated gif image out of several images.
#
# Dependencies: imagemagick
#
# Usage: gifit <file1> <file2> ...
#        gifit *.jpg
#
# Creator: Göran Gustafsson (gustafsson.g at gmail.com)
# License: BSD 3-Clause

if [[ ! $# -ge 2 ]]; then
  echo "Usage: ${0:t} [FILENAMES]..."
  exit
fi

for arg; do
  if [[ ! -f $arg ]]; then
    echo "File '${arg}' does not exist! Exiting..."
    exit 1
  fi
done

date=$(date '+%Y-%m-%d_%H%M')
filename=animated_${date}.gif
convert -delay 30 -loop 0 $* $filename

if [[ $OSTYPE == darwin* ]]; then
  open -a Safari $filename
fi
