#!/usr/bin/env zsh

# Description: This script either displays 20 history entries or displays
# entries all and use grep + the second argument to show the ones of interest.
#
# This script must be used from an alias. I have this in ~/.zshrc:
#
# alias h="source h"
#
# The source command before the script name must be there to make the script
# run in the current shell.
#
# Usage: h
#        h <pattern>
#
# Written by Göran Gustafsson (gustafsson.g at gmail.com).
# License: BSD 3-Clause.

if [[ $# -ge 1 ]]; then
  history -i 1 | grep --ignore-case "$*"
else
  history -20
fi
