#!/usr/bin/env zsh

# Description: Displays last 25 history entries. If argument is supplied only
# history entries that matches the pattern are displayed.
#
# Caveat: Script must be sourced to run in current shell.
# alias hist="source hist"
#
# Usage: hist
#        hist <pattern>
#
# Creator: Göran Gustafsson (gustafsson.g at gmail.com)
# License: BSD 3-Clause

if [[ $# -ge 1 ]]; then
  output=$(history -i 1 | grep --ignore-case "$*")

  if [[ -n $output ]]; then
    echo $output
  else
    echo "No matching entries found!"
  fi
else
  history -i 1 | eval $PAGER
fi
