#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

# Description: This script recursively searches the current working directory
# or a specified directory for files containing a specific pattern.

# Usage: hl <pattern> <file>
#        hl "<pattern>" <file>
#        command | hl <pattern>
#        command | hl "<pattern>"

if [[ $# -eq 1 ]]; then
  # The "|$" part is very important! It makes grep display all text.
  egrep --color "${*}|$"
elif [[ $# -eq 2 ]]; then
  egrep --color "${1}|$" $2
else
  echo "Usage: $0:t [PATTERN]... [FILENAME]..."
fi
