#!/usr/bin/env zsh

# Description: This script displays files modified within the last hour.
#
# Usage: lasth
#        lasth <path>
#
# Written by Göran Gustafsson (gustafsson.g at gmail.com).
# License: BSD 3-Clause.

if [[ $# -eq 0 ]]; then
  ls -l **/*(mh-1)
elif [[ $# -eq 1 ]]; then
  if [[ -d $1 ]]; then
    ls -l ${1}/**/*(mh-1)
  else
    echo "Path '${1}' is not a directory! Exiting..."
    exit 1
  fi
else
  echo "Usage: ${0:t} [PATH]..."
fi
