#!/usr/bin/env zsh

# Description: Downloads/updates Vim plugins with git.
#
# Usage: maint-vim
#
# Creator: Göran Gustafsson (gustafsson.g at gmail.com)
# License: BSD 3-Clause

pack_path=~/.vim/pack/others

function fetch {
  directory=${pack_path}/$1
  url=$2

  print -P "\n%F{cyan}Fetching plugin: ${directory:t}%f"
  if [[ -d ${directory}/.git ]]; then
    git -C $directory pull
  else
    git clone $url $directory
  fi
}

if [[ ! -d $pack_path ]]; then
  echo "Creating directory '${pack_path}'."
  mkdir -p $pack_path
  echo
fi

echo "Fetching Vim plugins."

fetch start/syntastic https://github.com/vim-syntastic/syntastic.git
fetch start/vim-go    https://github.com/fatih/vim-go.git
fetch start/vim-mundo https://github.com/simnalamburt/vim-mundo.git

fetch start/vim-commentary  https://github.com/tpope/vim-commentary.git
fetch start/vim-endwise     https://github.com/tpope/vim-endwise.git
fetch start/vim-repeat      https://github.com/tpope/vim-repeat.git
fetch start/vim-speeddating https://github.com/tpope/vim-speeddating.git
fetch start/vim-surround    https://github.com/tpope/vim-surround.git

echo "\nGenerating help tags for all plugins under ~/.vim/pack/*/start."
vim -c "helptags ALL" -c q
