#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

# Description: This script creates a directory (or several directories) and
# then changes the current working directory to the one just created.
#
# This script must be used from an alias. I have this in ~/.zshrc:
#
# alias mkcd="source mkcd"
#
# The source command before the script name must be there to make the script
# run in the current shell.

# Usage: mkcd <path>
#        mkcd <directory1/directory2/...>

if [[ ! $# -eq 1 ]]; then
  echo "Usage: ${0:t} [PATH]..."
  exit
fi

mkdir -p $1
cd $1
