#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

# Description: This script plays 56k modem sound and displays a progressbar
# while "connecting". The progressbar is synced with a specific audio file i
# found on the internetz.

# Dependencies: alsa-utils (on Linux)

# Usage: modem

sound_file=~/Storage/modem.mp3

if [[ $OSTYPE == darwin* ]]; then
  play_music="afplay $sound_file" # Comes with Mac OS X.
else
  play_music="aplay -q $sound_file" # Comes with alsa-utils.
fi

if [[ ! -f $sound_file ]]; then
  echo "Buu! Modem not plugged in! :("
  return 1
fi

echo "Dialing up 56k modem.\n"
eval $play_music & # Execute play_music.

echo -n "[            ]"
for number in {1..13}; do printf "\b"; done # Move cursor to the left.

sleep 3

for number in {1..12}; do
  print -nP "%B%F{black}#%f%b"
  sleep 1
done

echo -n "] "
print -P "%B%F{green}Connected!%f%b"

sleep 1
echo "\nEnjoy the internetz!"
sleep 1
