#!/usr/bin/env zsh

# Description: Run "nnn" and afterwards change directory in current shell.
#
# ~/.zshrc:
#
#   compdef _nnn n3
#   alias n3="source n3"
#
# Usage: n3
#
# Author: Göran Gustafsson (gustafsson.g at gmail.com)
# License: BSD 3-Clause

last_dir=~/.config/nnn/.lastd

nnn $*

if [[ -f $last_dir ]]; then
  source $last_dir && rm $last_dir &> /dev/null
fi
