#!/usr/bin/env zsh

# Description: Run "nnn" and afterwards change directory in current shell.
#
# ~/.zshrc:
#
#   compdef _nnn n3
#   alias n3="source n3"
#
# Usage: n3
#
# Author: Göran Gustafsson (gustafsson.g at gmail.com)
# License: BSD 3-Clause

if [[ $NNNLVL -ge 1 ]]; then
  echo "nnn is already running..."
  return
fi

if [[ -z $NNN_TMPFILE ]]; then
  export NNN_TMPFILE=${NNN_TMPFILE:-${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.lastd}
  clear_setting=1
fi

nnn $*

if [[ -f $NNN_TMPFILE ]]; then
  source $NNN_TMPFILE
  rm -f $NNN_TMPFILE > /dev/null
fi

if [[ $clear_setting -eq 1 ]]; then
  unset NNN_TMPFILE
fi
