#!/usr/bin/env zsh

# Description: Scan local network to find open network services.
#
# Usage: netscan
#
# Author: Göran Gustafsson (gustafsson.g at gmail.com)
# License: BSD 3-Clause

if [[ $OSTYPE == darwin* ]]; then
  # ffffff00
  hexmask=$(ifconfig en0 | awk '/inet /{print $4}' | sed -e 's/0x//')
  # 111111111111111111111111
  binmask=$(echo "ibase=16; obase=2; ${(U)hexmask}" | bc | sed -e 's/0//g')
  # 192.168.1.100/24
  network=$(ifconfig en0 | awk '/inet /{print $2}')/${#${binmask}}
else
  # 192.168.1.2/24
  network=$(ip addr show eth0 | awk '/inet /{print $2}')
fi
echo "Scanning network ${network}.\n"

# -sS (TCP SYN scan) is better but requires root privileges.
nmap -sT $network --open
