#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

# Not finished. Saving for future reference.

if [ ! -z $1 ] && [[ $# < 2 ]] && [ -f $1 ]; then
  WORDS=""

  egrep --color=auto -n -i "$WORDS" $1
else
  echo "Usage: $0 [FILENAME]..."
fi

