#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

# Description: This script displays the running processes and if a argument
# is supplied then only the processes that matches the pattern is displayed.
#
# I have this in ~/.zshrc to adjust the ps display options used:
#
# export ps_display="user,pid,command"

# Usage: p
#        p <pattern>

if [[ $# -gt 0 ]]; then
  if [[ ! -z $ps_display ]]; then
    command="ps ax -o $ps_display"
  else
    command="ps ax"
  fi

  # Run ps, remove header and ignore false results (script and grep).
  eval $command | tail -n +2 | egrep --invert-match "(grep $*|$0 $*)" | grep "$*" || echo "No processes found!"
else
  if [[ ! -z $ps_display ]]; then
    ps ax -o $ps_display
  else
    ps ax
  fi
fi
