#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

# Description: This script displays the running processes and if a argument
# is supplied then only the processes that matches the pattern is displayed.
#
# I have this in ~/.zshrc to adjust the ps display options used:
#
# export ps_display="user,pid,command"

# Usage: p
#        p <pattern>

if [[ ! -z $ps_display ]]; then
  command="ps ax -o $ps_display"
else
  command="ps ax"
fi

if [[ $# -gt 0 ]]; then
  ps_output=$(eval $command)

  # Skip the first row and ignore the text "zsh /Users/GLEG/Scripts/p x".
  ps_body=$(echo $ps_output | \
    tail -n +2 | \
    egrep --invert-match "zsh $0 $*" | \
    grep "$*")

  if [[ ! -z $ps_body ]]; then
    echo $ps_output | head -n 1 # Print the ps header.
    echo $ps_body | grep "$*"   # Run "grep" again for colored output.
  else
    echo "No processes found!"
  fi
else
  eval $command
fi
