#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

# Description: This script displays the running processes and if a argument is
# supplied then only the processes that matches the pattern is displayed.

# Usage: p
#        p <pattern>

ps_command="ps ax -o user,pid,command"

if [[ $# -ge 1 ]]; then
  ps_output=$(eval $ps_command)

  # Skip the first row and ignore the text "zsh /Users/GLEG/Scripts/p x" and
  # "ps ax -o user,pid,command".
  ps_body=$(echo $ps_output | \
    tail -n +2 | \
    egrep --invert-match "(zsh $0 ${*}|${ps_command})" | \
    grep --ignore-case "$*")

  if [[ ! -z $ps_body ]]; then
    echo $ps_output | head -n 1 # Print the ps header.
    echo $ps_body | grep --ignore-case "$*" # Run again for colored output.
  else
    echo "No processes found!"
  fi
else
  eval $ps_command
fi
