#!/usr/bin/env zsh

# Description: This script changes the permissions on all files and directories
# under the specified path(s). The permissions used are 700 for directories and
# 600 (or 700) for files. It also removes ACLs under OS X.
#
# Usage: perms <path1> <path2> ...
#
# Written by Göran Gustafsson (gustafsson.g at gmail.com).
# License: BSD 3-Clause.

if [[ $# -eq 0 ]]; then
  echo "Usage: ${0:t} [PATH(S)]..."
  exit
fi

perm_dir=700
perm_file=600
perm_exec=$perm_dir

for arg; do
  if [[ ! -a $arg ]]; then
    echo "Item '${arg}' does not exist! Skipping..."
    continue
  fi

  echo "Changing permissions on: ${arg}"

  if [[ $OSTYPE == darwin* ]]; then
    find $arg -type d -exec chmod -N "{}" \; -exec chmod $perm_dir "{}" \;

    find $arg -type f -perm +111 \
      -exec chmod -N "{}" \; \
      -exec chmod $perm_exec "{}" \;

    find $arg -type f ! -perm +111 \
      -exec chmod -N "{}" \; \
      -exec chmod $perm_file "{}" \;
  else
    find $arg -type d -exec chmod $perm_dir "{}" \;
    find $arg -type f -perm /111 -exec chmod $perm_exec "{}" \;
    find $arg -type f ! -perm /111 -exec chmod $perm_file "{}" \;
  fi
done
