#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

# Description: This script changes the permissions on all files and
# directories under the specified path (including the root directory). The
# permissions used are 700 for directories and 600 for files. It also removes
# all of the extra permission attributes under OS X.

# Usage: perms <path>

if [[ ! $# -eq 1 ]]; then
  echo "Usage: $0:t [PATH]..."
  exit
fi

if [[ ! -d $* ]]; then
  echo "Directory '$*' does not exist!"
  return 1
fi

echo "Changing permissions recursively on directory '$*'."

if [[ $OSTYPE == darwin* ]]; then
  find $* -type d -exec chmod -N "{}" \; -exec chmod 700 "{}" \;
  find $* -type f -exec chmod -N "{}" \; -exec chmod 600 "{}" \;
else
  find $* -type d -exec chmod 700 "{}" \;
  find $* -type f -exec chmod 600 "{}" \;
fi
