#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

# Description: This script prints out the name of a random file/directory from
# the current directory or a specified one.

# Usage: randf
#        randf <path>

if [[ $# -eq 0 ]]; then
  files=(*)
  echo $files[$RANDOM%${#files}+1]
elif [[ $# -eq 1 ]]; then
  if [[ -d $1 ]]; then
    files=(${1}/*)
    echo $files[$RANDOM%${#files}+1]
  else
    echo "Path '${1}' is not a directory! Exiting..."
    exit 1
  fi
else
  echo "Usage: ${0:t} [PATH]..."
fi
