#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

# Description: This script displays the 10 most recently modified
# files/directories inside a directory.

# Usage: recf
#        recf <path>

if [[ $# -eq 0 ]]; then
  ls -t | head
elif [[ $# -eq 1 ]]; then
  if [[ -d $1 ]]; then
    ls -t $1 | head
  else
    echo "Path '${1}' is not a directory! Exiting..."
    exit 1
  fi
else
  echo "Usage: ${0:t} [PATH]..."
fi
