#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

# Description: This script recursively searches the current working directory
# or a specified directory for files containing a specific pattern.

# Usage: rgrep <pattern>
#        rgrep <pattern> <path>
#        rgrep <"pattern">
#        rgrep <"pattern"> <path>

if [[ $# -eq 1 ]]; then
  grep --recursive $1 .
elif [[ $# -eq 2 ]]; then
  grep --recursive $*
else
  echo "Usage: $0:t [PATTERN]... [PATH]..."
fi
