#!/usr/bin/env zsh

# Description: This script fetches git repos, creates symlinks, directories etc
# so i can easily get my environment the way i want.

# Usage: setup_dotfiles

# Written by Göran Gustafsson (gustafsson.g at gmail.com).
# License: BSD 3-Clause.

if [[ ! $OSTYPE == darwin* ]]; then
  git clone https://github.com/ggustafsson/IP-Kalkylatorn.git ~/Projects/IP\ Kalkylatorn
  git clone https://github.com/ggustafsson/Ninja-Color-Scheme.git ~/Projects/Ninja\ Color\ Scheme
  git clone https://github.com/ggustafsson/Tim.git ~/Projects/Tim

  mkdir ~/.ssh
fi

ln -s ~/Projects/Dot\ Files/Scripts ~/Scripts
ln -s ~/Projects/Dot\ Files/gitconfig ~/.gitconfig
ln -s ~/Projects/Dot\ Files/gitignore_global ~/.gitignore_global
ln -s ~/Projects/Dot\ Files/ssh_config ~/.ssh/config
ln -s ~/Projects/Dot\ Files/timrc ~/.timrc
ln -s ~/Projects/Dot\ Files/tmux.conf ~/.tmux.conf
ln -s ~/Projects/Dot\ Files/vimrc ~/.vimrc
ln -s ~/Projects/Dot\ Files/zshenv ~/.zshenv
ln -s ~/Projects/Dot\ Files/zshrc ~/.zshrc

if [[ $OSTYPE == darwin* ]]; then
  ln -s ~/Projects/Dot\ Files/gvimrc ~/.gvimrc
  ln -s ~/Projects/hammerspoon ~/.hammerspoon
else
  ln -s ~/Projects/IP\ Kalkylatorn/ipkalk ~/Scripts/ipkalk
  ln -s ~/Projects/Tim/tim ~/Scripts/tim
fi

mkdir ~/.vim
mkdir ~/.vim/autoload
mkdir ~/.vim/backups
mkdir ~/.vim/bundle
mkdir ~/.vim/colors
mkdir ~/.vim/undos

~/Scripts/dl_vim install

ln -s ~/.vim/pathogen/autoload/pathogen.vim ~/.vim/autoload/
ln -s ~/Projects/Dot\ Files/vim/syntax ~/.vim/syntax
ln -s ~/Projects/Dot\ Files/vim/templates ~/.vim/templates
ln -s ~/Projects/Ninja\ Color\ Scheme/colors/ninja.vim ~/.vim/colors/
