#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

# Description: This script joins a specific IRC channel and slaps someone.

# Usage: slapbot2000 <nick> <item>

server=se.quakenet.org
port=6667
channel=#degiz
irc_stream=/tmp/irc_stream

if [[ ! $# -eq 2 ]]; then
  echo "Usage: ${0:t} [NICK]... [ITEM]..."
  exit
fi

echo "NICK slapbot2000" | tee $irc_stream
echo "USER slapbot 0 * :Slapping bot 2000" | tee -a $irc_stream

tail -f $irc_stream | nc -i 1 $server $port | while read message; do
  echo $message

  if [[ $message == PING* ]]; then
    echo "PONG${message#PING}" | tee -a $irc_stream
    sleep 5
    echo "JOIN $channel" | tee -a $irc_stream
    echo -e "PRIVMSG $channel :\x01ACTION slaps $1 around a bit with a large $2\x01" | tee -a $irc_stream
    echo "QUIT :Hehehe" | tee -a $irc_stream
    sleep 2
    rm $irc_stream
    exit
  fi
done
