#!/usr/bin/env zsh

# Description: Scan the LAN for open network services (FTP, SSH, HTTP, HTTPS,
# SMB, AFP and VNC).
#
# Dependencies: nmap
#
# Usage: servf
#
# Written by Göran Gustafsson (gustafsson.g at gmail.com).
# License: BSD 3-Clause.

if [[ $OSTYPE == darwin* ]]; then
  # Yes, /24 is hard-coded. Who cares?!
  network=$(ifconfig en0 | awk '/inet /{print $2}')/24
else
  network=$(ip addr show eth0 | awk '/inet /{print $2}')
fi

# Port 21   = FTP
# Port 22   = SSH
# Port 80   = HTTP
# Port 443  = HTTPS
# Port 445  = SMB
# Port 548  = AFP
# Port 5900 = VNC
# Port 8080 = Alternative HTTP
ports="21,22,80,443,445,548,5900,8080"

echo "Scanning network..."

results=$(nmap -sT $network -p $ports --open 2> /dev/null | \
  egrep -v "(Host is up|Not shown)" | \
  tail -n +3 | head -n -2)

if [[ ! -z $results ]]; then
  echo "\n$results"
else
  echo "\nNo services found on network!"
fi
