#!/usr/bin/env zsh

# Description: This script prints out the content of my $TODO_FILE file or adds
# a new entry to the top of the file. The variable TODO_FILE is set from
# ~/.zshrc with "export TODO_FILE=path".
#
# I use the following in Vim:
# nnoremap <Leader>to :edit ~/Documents/Text\ Files/To-do\ List.txt<CR>
#
# Usage: t
#        t <text>
#
# Written by Göran Gustafsson (gustafsson.g at gmail.com).
# License: BSD 3-Clause.

if [[ -z $TODO_FILE ]]; then
  echo "Variable 'TODO_FILE' is not set! Exiting..."
  exit 1
fi

if [[ $# -ge 1 ]]; then
  echo "Adding to-do entry."
  if [[ -f $TODO_FILE ]]; then
    cp $TODO_FILE ${TODO_FILE}.tmp
    echo $* > $TODO_FILE
    cat ${TODO_FILE}.tmp >> $TODO_FILE
    rm ${TODO_FILE}.tmp
  else
    echo $* > $TODO_FILE
  fi
else
  if [[ ! -f $TODO_FILE ]]; then
    echo "File '${TODO_FILE}' does not exist! Exiting..."
    exit 1
  fi

  cat $TODO_FILE
fi
