#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

# Description: This script prints out the content of my $todo_file file or
# adds a new entry to the bottom of the file. todo_file is set from ~/.zshrc
# with "export todo_file=path".

# Usage: t
#        t <text>

if [[ -z $todo_file ]]; then
  echo "Variable 'todo_file' is not set! Exiting..."
  return 1
fi

if [[ $# -gt 0 ]]; then
  if [[ -f $todo_file ]]; then
    echo "- $*" >> $todo_file
  else
    echo "- $*" > $todo_file
  fi
  echo "Added new entry to to-do file."
else
  if [[ -f $todo_file ]]; then
    if [[ -s $todo_file ]]; then
      echo "${todo_file:t}:\n"
      cat $todo_file
    else
      echo "The to-do file is empty!"
    fi
  else
    echo "The to-do file does not exist!"
  fi
fi
