#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

# Description: This script prints out the content of my $TODO_FILE file or
# adds a new entry to the bottom of the file. TODO_FILE is set from ~/.zshrc
# with "export TODO_FILE=path".

# Usage: t
#        t <text>

if [[ -z $TODO_FILE ]]; then
  echo "Variable TODO_FILE is not set! Exiting..."
  return 1
fi

if [[ $# -gt 0 ]]; then
  if [[ -f $TODO_FILE ]]; then
    echo "- $*" >> $TODO_FILE
  else
    echo "- $*" > $TODO_FILE
  fi
  echo "Added new entry to to-do file."
else
  if [[ -f $TODO_FILE ]]; then
    if [[ -s $TODO_FILE ]]; then
      echo "${TODO_FILE:t}:\n"
      cat $TODO_FILE
    else
      echo "The to-do file is empty!"
    fi
  else
    echo "The to-do file does not exist!"
  fi
fi
