#!/usr/bin/env zsh

# Description: This script prints out the different terminal colors.

# Usage: tcolors

# Written by Göran Gustafsson (gustafsson.g at gmail.com).
# License: BSD 3-Clause.

for number in {30..37}; do
  echo -n "\033[0;${number}m0;${number}m\033[0m "
done && echo

for number in {30..37}; do
  echo -n "\033[1;${number}m1;${number}m\033[0m "
done && echo

for number in {40..47}; do
  echo -n "\033[1;${number}m1;${number}m\033[0m "
done && echo
