#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

# Description: This script prints out the different terminal colors.

# Usage: tcolors

for NUMBER in {30..37} ; do
  echo -n "\033[0;${NUMBER}m0;${NUMBER}m\033[0m "
done

echo

for NUMBER in {30..37} ; do
  echo -n "\033[1;${NUMBER}m1;${NUMBER}m\033[0m "
done

echo

for NUMBER in {40..47} ; do
  echo -n "\033[1;${NUMBER}m1;${NUMBER}m\033[0m "
done

echo
