#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

# Description: This script prints out the different terminal colors.

# Usage: tcolors

for number in {30..37}; do
  echo -n "\033[0;${number}m0;${number}m\033[0m "
done && echo

for number in {30..37}; do
  echo -n "\033[1;${number}m1;${number}m\033[0m "
done && echo

for number in {40..47}; do
  echo -n "\033[1;${number}m1;${number}m\033[0m "
done && echo
