#!/usr/bin/env ruby

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

# Description: This script takes text as input and prints out text that is
# capitalized as a headline. Should be correct most of the time.

# Usage: title <text>

word_list = %w(a an and as at but by en for if in of on or the to via vs)

# Using .join and .split to turn the argument(s) into one single string.
text = $*.join(" ").split(" ")
position = 0

text.each do |word|
  # Check if the current word (lower cased) is included in the word_list
  # array. Capitalize the first word no matter what.
  if word_list.include?(word.downcase) and position > 0
    text[position] = word.downcase
  else
    text[position] = word.capitalize
  end

  position += 1
end

puts text.join(" ")
