#!/usr/bin/env zsh

# Description: Start new (or attach existing) custom Tmux sessions.
#
# Usage: tmux-init
#
# Author: Göran Gustafsson (gustafsson.g at gmail.com)
# License: BSD 3-Clause

session1=ABC
session2=XYZ
session3=123

# For future reference:
#   split-window -h creates vertically divided panes...
#   split-window -v creates horizontally divided panes...

tmux new-session -d -s $session1
tmux new-session -d -s $session2

if [[ $HOST == Twoson ]]; then
  tmux new-session -d -s $session3
fi

# Don't attach if already inside of Tmux.
if [[ -z $TMUX ]]; then
  tmux attach-session -t $session1
fi
