#!/usr/bin/env zsh

# Description: Start custom Tmux documentation setup.
#
# Usage: tmux-docs
#
# Author: Göran Gustafsson (gustafsson.g at gmail.com)
# License: BSD 3-Clause

dir=~/Documents/Text

tmux \
  new-window -c $dir nvim -c "call DocsMode()" \; \
  rename-window docs
