#!/usr/bin/env zsh

# Description: Start new (or attach existing) custom Tmux session.
#
# Usage: tmux-init
#
# Creator: Göran Gustafsson (gustafsson.g at gmail.com)
# License: BSD 3-Clause

session1=misc
session2=dev

# For future reference:
#   -h creates vertically divided panes...
#   -v creates horizontally divided panes...

tmux \
  new-session -d -s $session1 \; \
  rename-window main \; \
  new-window -n secondary \; \
  split-window -h \; \
  select-pane -L \; \
  select-window -t :1

tmux \
  new-session -d -s $session2 -c ~/Projects \; \
  rename-window main \; \
  new-window -n secondary -c ~/Projects \; \
  split-window -h -c ~/Projects \; \
  select-pane -L \; \
  select-window -t :1

if [[ -z $TMUX ]]; then
  tmux attach-session -t $session1
fi
