#!/usr/bin/env zsh

# Description: Start custom Tmux documentation setup.
#
# ~/.tmux.conf:
#
#   bind Enter menu -T "#[align=centre] Launcher " \
#     "Docs Mode" 2 "run-shell tmux-docs"
#
# Usage: tmux-docs
#
# Author: Göran Gustafsson (gustafsson.g at gmail.com)
# License: BSD 3-Clause

tmux \
  new-window nvim -c "call DocsMode()" \; \
  rename-window docs
