#!/usr/bin/env zsh

# Description: Start custom Tmux development setup.
#
# ~/.tmux.conf:
#
#   bind Enter menu -T "#[align=centre] Launcher " \
#     "Dev Mode" 1 "run-shell tmux-dev"
#
# Usage: tmux-dev
#
# Author: Göran Gustafsson (gustafsson.g at gmail.com)
# License: BSD 3-Clause

tmux \
  new-window nvim -c "call DevMode()" \; \
  rename-window dev
