#!/usr/bin/env zsh

# Description: Start new (or attach existing) custom Tmux session.
#
# Usage: tmux-init
#
# Creator: Göran Gustafsson (gustafsson.g at gmail.com)
# License: BSD 3-Clause

session1=misc
session2=dev

# For future reference:
#   split-window -h creates vertically divided panes...
#   split-window -v creates horizontally divided panes...

tmux \
  new-session -d -s $session1 \;

tmux \
  new-session -d -s $session2 -c ~/Projects \; \
  send-keys "chkp" C-l Enter \;

if [[ -z $TMUX ]]; then
  tmux attach-session -t $session1
fi
