#!/usr/bin/env zsh

# Description: Start custom Tmux development setup.
#
# ~/.tmux.conf:
#
#   bind Enter menu -T "#[align=centre] Launcher " \
#     "Dev Mode" 1 "run-shell 'tmux-dev \"#{pane_current_path}\"'"
#
# Usage: tmux-dev
#        tmux-dev <path>
#
# Author: Göran Gustafsson (gustafsson.g at gmail.com)
# License: BSD 3-Clause

if [[ -d $1 ]]; then
  nvim_cmd="call DevMode('${1:a}')"
else
  nvim_cmd="call DevMode()"
fi

tmux \
  new-window nvim -c "$nvim_cmd" \; \
  rename-window dev
