#!/usr/bin/env zsh

# Description: Start new (or attach existing) custom Tmux sessions.
#
# Usage: tmuxa
#
# Creator: Göran Gustafsson (gustafsson.g at gmail.com)
# License: BSD 3-Clause

session1=home
session2=work

# For future reference:
#   split-window -h creates vertically divided panes...
#   split-window -v creates horizontally divided panes...

tmux new-session -d -s $session1
tmux new-session -d -s $session2
tmux new-session -d -s $session3

if [[ -z $TMUX ]]; then
  tmux attach-session -t $session1
fi
