#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

# Description: This script sets up tmux work session.

# Usage: tmw

session=work

if ! tmux attach -t $session &> /dev/null; then
  # \; is used to chain tmux commands.
  tmux new-session -s $session \; \
    send-keys "vim" enter \; \
    split-window -h \; \
    send-keys "cd ~/Downloads" enter \; \
    send-keys C-l \; \
    send-keys "d" enter \; \
    attach
fi
