#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

# Description: This script sets up tmux work session.

# Usage: tmw

session=work

if ! tmux attach -t $session &> /dev/null; then
  # \; is used to chain tmux commands.
  tmux new-session -s $session \; \
    new-window -d \; \
    split-window -h \; \
    send-keys -t 0 "vim" enter \; \
    send-keys -t 1 "cd ~/Downloads" enter \; \
    send-keys -t 1 C-l \; \
    send-keys -t 1 "d" enter
fi
