#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

# Description: This script makes it easy to extract files from all of the most
# common compressed file types.

# Usage: unp <file(s)>

if [[ $# -gt 0 ]]; then
  for argument in $*; do
    if [[ -f $argument ]]; then
      case $argument in
        *.bz2)
          if [[ $argument == *.tar.bz2 ]]; then
            tar xvjf $argument
          else
            bunzip2 $argument
          fi
        ;;
        *.gz)
          if [[ $argument == *.tar.gz ]]; then
            tar zxvf $argument
          else
            gunzip $argument
          fi
        ;;
        *.rar)  unrar x    $argument ;;
        *.tar)  tar xvf    $argument ;;
        *.tbz2) tar xvjf   $argument ;;
        *.tgz)  tar zxvf   $argument ;;
        *.Z)    uncompress $argument ;;
        *.zip)  unzip      $argument ;;
        *.7z)   7z x       $argument ;;
        *)
          echo "File '$argument' cannot be extracted via $0:t."
        ;;
      esac
    else
      echo "File '$argument' does not exist."
    fi
  done
else
  echo "Usage: $0:t [FILENAME(S)]..."
fi
