#!/usr/bin/env zsh

# Description: This script makes it easy to extract files from all of the most
# common compressed file types.

# Dependencies: p7zip and unrar

# Usage: unp <file(s)>

# Written by Göran Gustafsson (gustafsson.g at gmail.com).
# License: BSD 3-Clause.

if [[ $# -eq 0 ]]; then
  echo "Usage: ${0:t} [FILENAME(S)]..."
  exit
fi

echo "Extracting archive(s)."

for arg; do
  echo

  if [[ ! -f $arg ]]; then
    echo "File '${arg}' does not exist! Skipping..."
    continue
  fi

  echo "Unpacking file '${arg}'."

  case $arg in
    *.tar.bz2) tar xvf $arg ;; # Must come before "*.bz2".
    *.bz2)     bunzip2 $arg ;;

    *.tar.gz)  tar xvf $arg ;; # Must come before "*.gz".
    *.gz)      gunzip $arg  ;;

    *.tar.xz)  tar xvf $arg ;; # Must come before "*.xz".
    *.xz)      unxz $arg    ;;

    *.rar)     unrar x $arg    ;;
    *.tar)     tar xvf $arg    ;;
    *.tbz2)    tar xvf $arg    ;;
    *.tgz)     tar xvf $arg    ;;
    *.zip)     unzip $arg      ;;
    *.Z)       uncompress $arg ;;
    *.7z)      7z x $arg       ;;

    *)
      echo "File '${arg}' cannot be extracted with ${0:t}!"
    ;;
  esac
done
