#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

# Description: This script makes it easy to validate HTML files through
# http://validator.w3.org via the terminal.
#
# I have this in ~/.vimrc so i can easily validate files inside of Vim:
#
# nnoremap <Leader>w3 :!~/Scripts/validate "%"<CR>

# Usage: validate <file(s)>

if [[ $# -gt 0 ]]; then
  echo "Validating HTML file(s)."

  for file in $*; do
    if [[ -f $file ]]; then
      if [[ $file == *.html ]]; then
        # Change the directory to where the file is. Otherwise the upload won't work :(
        cd $file:A:h

        echo "\nValidating the file '$file'."

        results=$(curl --form "uploaded_file=@${file:t};type=text/html" --form output=json --silent http://validator.w3.org/check)

        if [[ $? -gt 0 ]]; then
          echo "Failed at getting results!"
          return 1
        fi

        # Only work with lines that contain information about errors.
        parsed=$(echo $results | grep '"lastLine":')

        if [[ ! -z $parsed ]]; then
          echo "\nFound error(s) on line(s):\n"
          # Remove all the crap and only display uniq errors. Must use "sort" to make "uniq" work.
          echo $parsed | sed 's/^[ \t]*"lastLine":/ /;s/,//g' | sort --general-numeric-sort | uniq
        else
          echo "No errors! :)"
        fi
      else
        echo "File '$1' does not end with html."
        return 1
      fi
    else
      echo "File '$1' does not exist."
    fi
  done
else
  echo "Usage: $0:t [FILENAME(S)]..."
fi
