#!/usr/bin/env zsh

# Description: Nvim equivalent of Vim's "view" with additional quit mapping.
# Using script instead of alias to allow for usage in Tmux and other scripts.
#
# Usage: view
#        view <path>
#
# Author: Göran Gustafsson (gustafsson.g at gmail.com)
# License: BSD 3-Clause

nvim -R -c "nmap q <Cmd>q<CR>" -c "set nolist" $*
