#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

# Description: This script automatically downloads several Vim related git
# repositories i want to keep up-to-date.

# Usage: vimp

if [[ -d ~/.vim/pathogen ]]; then
  print -P "%B%F{green}Checking for Pathogen updates.%f%b"
  cd ~/.vim/pathogen
  git pull
else
  git clone git://github.com/tpope/vim-pathogen.git ~/.vim/pathogen
fi

echo

if [[ -d ~/.vim/bundle/gist ]]; then
  print -P "%B%F{green}Checking for Gist updates.%f%b"
  cd ~/.vim/bundle/gist
  git pull
else
  git clone git://github.com/mattn/gist-vim.git ~/.vim/bundle/gist
fi

echo

if [[ -d ~/.vim/bundle/gundo ]]; then
  print -P "%B%F{green}Checking for Gundo updates.%f%b"
  cd ~/.vim/bundle/gundo
  git pull
else
  git clone git://github.com/sjl/gundo.vim.git ~/.vim/bundle/gundo
fi

echo

if [[ -d ~/.vim/bundle/lusty ]]; then
  print -P "%B%F{green}Checking for Lusty updates.%f%b"
  cd ~/.vim/bundle/lusty
  git pull
else
  git clone git://github.com/sjbach/lusty.git ~/.vim/bundle/lusty
fi

echo

if [[ -d ~/.vim/bundle/nerdcommenter ]]; then
  print -P "%B%F{green}Checking for NERDCommenter updates.%f%b"
  cd ~/.vim/bundle/nerdcommenter
  git pull
else
  git clone git://github.com/scrooloose/nerdcommenter.git ~/.vim/bundle/nerdcommenter
fi

echo

if [[ -d ~/.vim/bundle/nerdtree ]]; then
  print -P "%B%F{green}Checking for NERDTree updates.%f%b"
  cd ~/.vim/bundle/nerdtree
  git pull
else
  git clone git://github.com/scrooloose/nerdtree.git ~/.vim/bundle/nerdtree
fi

echo

if [[ -d ~/.vim/bundle/seek ]]; then
  print -P "%B%F{green}Checking for Seek updates.%f%b"
  cd ~/.vim/bundle/seek
  git pull
else
  git clone git://github.com/goldfeld/vim-seek.git ~/.vim/bundle/seek
fi

echo

if [[ -d ~/.vim/bundle/surround ]]; then
  print -P "%B%F{green}Checking for Surround updates.%f%b"
  cd ~/.vim/bundle/surround
  git pull
else
  git clone git://github.com/tpope/vim-surround.git ~/.vim/bundle/surround
fi

echo

if [[ -d ~/.vim/bundle/webapi ]]; then
  print -P "%B%F{green}Checking for WebAPI updates.%f%b"
  cd ~/.vim/bundle/webapi
  git pull
else
  git clone git://github.com/mattn/webapi-vim.git ~/.vim/bundle/webapi
fi
