#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

DLPATH=~/Sites/Frameworks

rm -rf ~/Sites/Frameworks\ Backups
cp -R $DLPATH ~/Sites/Frameworks\ Backups

if [ -d $DLPATH/bootstrap ]; then
  echo "\033[1;32mChecking for Bootstrap updates.\033[0m"
  cd $DLPATH/bootstrap
  git pull
else
  git clone git://github.com/twitter/bootstrap.git $DLPATH/bootstrap
fi

echo

if [ -d $DLPATH/chosen ]; then
  echo "\033[1;32mChecking for Chosen updates.\033[0m"
  cd $DLPATH/chosen
  git pull
else
  git clone git://github.com/harvesthq/chosen.git $DLPATH/chosen
fi

echo

if [ -d $DLPATH/css3-facebook-buttons ]; then
  echo "\033[1;32mChecking for CSS3 Facebook Buttons updates.\033[0m"
  cd $DLPATH/css3-facebook-buttons
  git pull
else
  git clone git://github.com/necolas/css3-facebook-buttons.git $DLPATH/css3-facebook-buttons
fi

echo

if [ -d $DLPATH/css3-github-buttons ]; then
  echo "\033[1;32mChecking for CSS3 GitHub Buttons updates.\033[0m"
  cd $DLPATH/css3-github-buttons
  git pull
else
  git clone git://github.com/necolas/css3-github-buttons.git $DLPATH/css3-github-buttons
fi

echo

if [ -d $DLPATH/deck.js ]; then
  echo "\033[1;32mChecking for Deck.js updates.\033[0m"
  cd $DLPATH/deck.js
  git pull
else
  git clone git://github.com/imakewebthings/deck.js.git $DLPATH/deck.js
fi

echo

if [ -d $DLPATH/impress.js ]; then
  echo "\033[1;32mChecking for Impress.js updates.\033[0m"
  cd $DLPATH/impress.js
  git pull
else
  git clone git://github.com/bartaz/impress.js.git $DLPATH/impress.js
fi

echo

if [ -d $DLPATH/jquery-rss ]; then
  echo "\033[1;32mChecking for jQuery RSS updates.\033[0m"
  cd $DLPATH/jquery-rss
  git pull
else
  git clone git://github.com/dawanda/jquery-rss.git $DLPATH/jquery-rss
fi

mkdir $DLPATH/jQuery

open 'http://docs.jquery.com/Downloading_jQuery#Current_Release'

date > $DLPATH/latest_update.txt

