#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

# Description: This script automatically downloads several web programming
# related git repositories i want to keep up-to-date.

# Usage: webf

DLPATH=~/Sites/Frameworks

if [[ -d $DLPATH/jQuery\ RSS ]]; then
  print -P "%B%F{green}Checking for jQuery RSS updates.%f%b"
  cd $DLPATH/jQuery\ RSS
  git pull
else
  git clone git://github.com/sdepold/jquery-rss.git $DLPATH/jQuery\ RSS
fi

[[ ! -d $DLPATH/Bootstrap ]] && mkdir $DLPATH/Bootstrap
if [[ $OSTYPE == darwin* ]]; then
  open http://twitter.github.com/bootstrap
else
  links http://twitter.github.com/bootstrap
fi

[[ ! -d $DLPATH/jQuery ]] && mkdir $DLPATH/jQuery
if [[ $OSTYPE == darwin* ]]; then
  open http://jquery.com/download
else
  links http://jquery.com/download
fi
