#!/usr/bin/env bash

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

rm -rf ~/Sites/Frameworks\ Backups

mv ~/Sites/Frameworks ~/Sites/Frameworks\ Backups
mkdir ~/Sites/Frameworks

cd ~/Sites/Frameworks

git clone git://github.com/bartaz/impress.js.git; echo
git clone git://github.com/dawanda/jquery-rss.git; echo
git clone git://github.com/imakewebthings/deck.js.git; echo
git clone git://github.com/necolas/css3-facebook-buttons.git; echo
git clone git://github.com/necolas/css3-github-buttons.git; echo
git clone git://github.com/twitter/bootstrap.git; echo

mkdir ~/Sites/Frameworks/jQuery

open 'http://docs.jquery.com/Downloading_jQuery#Current_Release'

date > ~/Sites/Frameworks/latest_update.txt

