#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

CURRENT_DIRECTORY=$PWD

for DIRECTORY in ~/Projects/*; do
  cd $DIRECTORY

  if [[ -n $(git rev-list origin..HEAD 2> /dev/null) ]]; then
    print -P "%B%F{cyan}$DIRECTORY:t:%f%b"
    git status -s -b
    echo
  elif [[ -n $(git status -s 2> /dev/null) ]]; then
    print -P "%B%F{red}$DIRECTORY:t:%f%b"
    git status -s -b
    echo
  elif [ -d .git ]; then
    CLEAN_BRANCH="$CLEAN_BRANCH * $DIRECTORY:t\n"
  fi
done

print -P "%B%F{green}Clean branches:%f%b"
echo -n "$CLEAN_BRANCH"
[ -z $CLEAN_BRANCH ] && echo

cd $CURRENT_DIRECTORY

