#!/usr/bin/env ruby

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

# Description: This script reads the file ~/.countdowns and calculates the
# remaining days until the specific date on each entry in the file.
#
# An entry in the file looks like this:
#
# "Title here", 2017, 01, 14

# Usage: countd

require "csv"

file = "#{Dir.home}/.countdowns"
today = Date.today
pos = 0

if not File.exists?(file)
  abort "File not found!"
elsif CSV.read(file).length == 0
  abort "No entries found!"
end

CSV.foreach(file) do |row|
  puts if pos > 0 # Print empty line before all countdowns except the first.
  if row.size != 4 # Skip unless 4 columns exist on a row.
    puts "The row on line #{pos + 1} is not 4 columns. Skipping!"
    next
  end

  title = row[0]

  year  = row[1].to_i
  month = row[2].to_i
  day   = row[3].to_i

  future = Date.new(year, month, day)
  days_left = (future - today).to_i

  case days_left
  when -1, 1
    day_or_days = "day"
  else
    day_or_days = "days"
  end

  puts title
  # Example: 24 days left until 2013-01-18
  puts "#{days_left} #{day_or_days} left until #{year}-#{"%02d" % month}-#{"%02d" % day}"

  pos += 1
end
