#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

# Description: This script performs a case insensitive search for files under
# the current working directory and prints out the full path to them.

# Usage: ffp <pattern>

if [[ $# -eq 1 ]]; then
  find -L "$PWD" -iname $1
else
  echo "Usage: $0:t [PATTERN]..."
fi
