#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

# Description: This script automatically downloads several miscellaneous git
# repositories i want to keep up-to-date.

# Usage: otherd

if [ -d ~/Development/Hello\ World ]; then
  print -P "%B%F{green}Checking for Hello World updates.%f%b"
  cd ~/Development/Hello\ World
  git pull
else
  git clone git://github.com/leachim6/hello-world.git ~/Development/Hello\ World
fi

echo

if [ -d ~/Documents/Reading/Dive\ Into\ HTML5/HTML ]; then
  print -P "%B%F{green}Checking for Dive Into HTML5 updates.%f%b"
  cd ~/Documents/Reading/Dive\ Into\ HTML5/HTML
  git pull
else
  git clone git://github.com/diveintomark/diveintohtml5.git ~/Documents/Reading/Dive\ Into\ HTML5/HTML
fi

echo

if [ -d ~/Documents/Reading/Dive\ Into\ Python\ 3/HTML ]; then
  print -P "%B%F{green}Checking for Dive Into Python 3 updates.%f%b"
  cd ~/Documents/Reading/Dive\ Into\ Python\ 3/HTML
  git pull
else
  git clone git://github.com/diveintomark/diveintopython3.git ~/Documents/Reading/Dive\ Into\ Python\ 3/HTML
fi

echo

if [ -d ~/Projects/Tim\ Fork ]; then
  print -P "%B%F{green}Checking for Tim (hdonnay fork) updates.%f%b"
  cd ~/Projects/Tim\ Fork
  git pull
else
  git clone git://github.com/hdonnay/Tim.git ~/Projects/Tim\ Fork
fi

echo

if [ -d ~/Storage/Fonts/Blackout ]; then
  print -P "%B%F{green}Checking for Blackout updates.%f%b"
  cd ~/Storage/Fonts/Blackout
  git pull
else
  git clone git://github.com/theleagueof/blackout.git ~/Storage/Fonts/Blackout
fi

echo

if [ -d ~/Storage/Fonts/Knewave ]; then
  print -P "%B%F{green}Checking for Knewave updates.%f%b"
  cd ~/Storage/Fonts/Knewave
  git pull
else
  git clone git://github.com/theleagueof/knewave.git ~/Storage/Fonts/Knewave
fi

echo

if [ -d ~/Storage/Fonts/League\ Gothic ]; then
  print -P "%B%F{green}Checking for League Gothic updates.%f%b"
  cd ~/Storage/Fonts/League\ Gothic
  git pull
else
  git clone git://github.com/theleagueof/league-gothic.git ~/Storage/Fonts/League\ Gothic
fi

echo

if [ -d ~/Storage/Fonts/Orbitron ]; then
  print -P "%B%F{green}Checking for Orbitron updates.%f%b"
  cd ~/Storage/Fonts/Orbitron
  git pull
else
  git clone git://github.com/theleagueof/orbitron.git ~/Storage/Fonts/Orbitron
fi

echo

if [ -d ~/Storage/Fonts/Ostrich\ Sans ]; then
  print -P "%B%F{green}Checking for Ostrich Sans updates.%f%b"
  cd ~/Storage/Fonts/Ostrich\ Sans
  git pull
else
  git clone git://github.com/theleagueof/ostrich-sans.git ~/Storage/Fonts/Ostrich\ Sans
fi

echo

if [ -d ~/Storage/Fonts/Prociono ]; then
  print -P "%B%F{green}Checking for Prociono updates.%f%b"
  cd ~/Storage/Fonts/Prociono
  git pull
else
  git clone git://github.com/theleagueof/prociono.git ~/Storage/Fonts/Prociono
fi

echo

if [ -d ~/Storage/Fonts/Sniglet ]; then
  print -P "%B%F{green}Checking for Sniglet updates.%f%b"
  cd ~/Storage/Fonts/Sniglet
  git pull
else
  git clone git://github.com/theleagueof/sniglet.git ~/Storage/Fonts/Sniglet
fi

