#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

if [[ $# -gt 0 ]]; then
  ps ax -o user,pid,%cpu,%mem,start,command | head -n 1
  ps ax -o user,pid,%cpu,%mem,start,command | tail -n +2 | egrep -v "(grep $*|$0 $*)" | grep "$*"
else
  ps ax -o user,pid,%cpu,%mem,start,command
fi

