#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

# Description: This script displays the running processes and if a argument
# is supplied then only the processes that matches the pattern is displayed.

# Usage: p
#        p <pattern>

if [[ $# -gt 0 ]]; then
  if [ ! -z $PS_OPTIONS ]; then
    ps ax -o $PS_OPTIONS | tail -n +2 | egrep -v "(grep $*|$0 $*)" | grep "$*"
  else
    ps ax | tail -n +2 | egrep -v "(grep $*|$0 $*)" | grep "$*"
  fi
else
  if [ ! -z $PS_OPTIONS ]; then
    ps ax -o $PS_OPTIONS
  else
    ps ax
  fi
fi

