#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

if [[ $# -gt 0 ]]; then
  if [[ $OSTYPE == darwin* ]]; then
    find $* -type d -exec chmod -N "{}" \; -exec chmod 755 "{}" \;
    find $* -type f -exec chmod -N "{}" \; -exec chmod 644 "{}" \;
  else
    find $* -type d -exec chmod 755 "{}" \;
    find $* -type f -exec chmod 644 "{}" \;
  fi
else
  echo "Usage: $0:t [PATH]..."
fi

