#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

if [ -z $TODO_FILE ]; then
  echo "Variable TODO_FILE is not set!"
  return 1
fi

if [[ $# -gt 0 ]]; then
  if [ -f $TODO_FILE ]; then
    sed '/^[#tab]*$/d' $TODO_FILE > $TODO_FILE.tmp
    echo "- $*\n" >> $TODO_FILE.tmp
    cat $TODO_FILE.tmp > $TODO_FILE && rm $TODO_FILE.tmp
  else
    echo "- $*\n" > $TODO_FILE
  fi
  echo "Added new entry to file."
else
  if [ -f $TODO_FILE ]; then
    echo "${TODO_FILE:t}:\n"
    sed '/^[#tab]*$/d' $TODO_FILE
  else
    echo "File does not exist!"
  fi
fi

