#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

[[ $# == 0 ]] && echo "Usage: $0:t [FILENAME(S)]..." && return

for ARGUMENT in $*; do
  if [ -f $ARGUMENT ]; then
    case $ARGUMENT in
      *.gz)
        if [[ $ARGUMENT == *.tar.gz ]]; then
          tar zxvf $ARGUMENT
        else
          gunzip $ARGUMENT
        fi
      ;;
      *.bz2)
        if [[ $ARGUMENT == *.tar.bz2 ]]; then
          tar xvjf $ARGUMENT
        else
          bunzip2 $ARGUMENT
        fi
      ;;
      *.tar)  tar xvf    $ARGUMENT ;;
      *.tgz)  tar zxvf   $ARGUMENT ;;
      *.tbz2) tar xvjf   $ARGUMENT ;;
      *.zip)  unzip      $ARGUMENT ;;
      *.rar)  unrar x    $ARGUMENT ;;
      *.Z)    uncompress $ARGUMENT ;;
      *.7z)   7z x       $ARGUMENT ;;
      *)
        echo "File $ARGUMENT cannot be extracted via $0:t."
      ;;
    esac
  else
    echo "File $ARGUMENT does not exist."
  fi
done

