#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

DLPATH=~/.vim/bundle

rm -rf ~/.vim/backups/bundle ~/.vim/backups/pathogen
cp -R ~/.vim/pathogen ~/.vim/backups/pathogen

if [ -d ~/.vim/pathogen ]; then
  echo "\033[1;32mChecking for Pathogen updates.\033[0m"
  cd ~/.vim/pathogen
  git pull
else
  git clone git://github.com/tpope/vim-pathogen.git ~/.vim/pathogen
fi

echo

cp -R $DLPATH ~/.vim/backups/bundle

if [ -d $DLPATH/gist ]; then
  echo "\033[1;32mChecking for Gist updates.\033[0m"
  cd $DLPATH/gist
  git pull
else
  git clone git://github.com/mattn/gist-vim.git $DLPATH/gist
fi

echo

if [ -d $DLPATH/gundo ]; then
  echo "\033[1;32mChecking for Gundo updates.\033[0m"
  cd $DLPATH/gundo
  git pull
else
  git clone git://github.com/sjl/gundo.vim.git $DLPATH/gundo
fi

echo

if [ -d $DLPATH/lusty ]; then
  echo "\033[1;32mChecking for Lusty updates.\033[0m"
  cd $DLPATH/lusty
  git pull
else
  git clone git://github.com/sjbach/lusty.git $DLPATH/lusty
fi

echo

if [ -d $DLPATH/nerdcommenter ]; then
  echo "\033[1;32mChecking for NERDCommenter updates.\033[0m"
  cd $DLPATH/nerdcommenter
  git pull
else
  git clone git://github.com/scrooloose/nerdcommenter.git $DLPATH/nerdcommenter
fi

echo

if [ -d $DLPATH/nerdtree ]; then
  echo "\033[1;32mChecking for NERDTree updates.\033[0m"
  cd $DLPATH/nerdtree
  git pull
else
  git clone git://github.com/scrooloose/nerdtree.git $DLPATH/nerdtree
fi

echo

if [ -d $DLPATH/nyancat ]; then
  echo "\033[1;32mChecking for NyanCat updates.\033[0m"
  cd $DLPATH/nyancat
  git pull
else
  git clone git://github.com/koron/nyancat-vim.git $DLPATH/nyancat
fi

echo

if [ -d $DLPATH/snipmate ]; then
  echo "\033[1;32mChecking for snipMate updates.\033[0m"
  cd $DLPATH/snipmate
  git pull
else
  git clone git://github.com/msanders/snipmate.vim.git $DLPATH/snipmate
fi

echo

if [ -d $DLPATH/surround ]; then
  echo "\033[1;32mChecking for Surround updates.\033[0m"
  cd $DLPATH/surround
  git pull
else
  git clone git://github.com/tpope/vim-surround.git $DLPATH/surround
fi

echo

if [ -d $DLPATH/viminesweeper ]; then
  echo "\033[1;32mChecking for Viminesweeper updates.\033[0m"
  cd $DLPATH/viminesweeper
  git pull
else
  git clone git://github.com/mfumi/viminesweeper.git $DLPATH/viminesweeper
fi

echo

if [ -d $DLPATH/webapi ]; then
  echo "\033[1;32mChecking for WebAPI updates.\033[0m"
  cd $DLPATH/webapi
  git pull
else
  git clone git://github.com/mattn/webapi-vim.git $DLPATH/webapi
fi

date > $DLPATH/latest_update.txt

