#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

DLPATH=~/.vim/bundle

rm -rf ~/.vim/backups/bundle ~/.vim/backups/pathogen
cp -R ~/.vim/pathogen ~/.vim/backups/pathogen

if [ -d ~/.vim/pathogen ]; then
  print -P "%B%F{green}Checking for Pathogen updates.%f%b"
  cd ~/.vim/pathogen
  git pull
else
  git clone git://github.com/tpope/vim-pathogen.git ~/.vim/pathogen
fi

echo

cp -R $DLPATH ~/.vim/backups/bundle

if [ -d $DLPATH/gist ]; then
  print -P "%B%F{green}Checking for Gist updates.%f%b"
  cd $DLPATH/gist
  git pull
else
  git clone git://github.com/mattn/gist-vim.git $DLPATH/gist
fi

echo

if [ -d $DLPATH/gundo ]; then
  print -P "%B%F{green}Checking for Gundo updates.%f%b"
  cd $DLPATH/gundo
  git pull
else
  git clone git://github.com/sjl/gundo.vim.git $DLPATH/gundo
fi

echo

if [ -d $DLPATH/lusty ]; then
  print -P "%B%F{green}Checking for Lusty updates.%f%b"
  cd $DLPATH/lusty
  git pull
else
  git clone git://github.com/sjbach/lusty.git $DLPATH/lusty
fi

echo

if [ -d $DLPATH/nerdcommenter ]; then
  print -P "%B%F{green}Checking for NERDCommenter updates.%f%b"
  cd $DLPATH/nerdcommenter
  git pull
else
  git clone git://github.com/scrooloose/nerdcommenter.git $DLPATH/nerdcommenter
fi

echo

if [ -d $DLPATH/nerdtree ]; then
  print -P "%B%F{green}Checking for NERDTree updates.%f%b"
  cd $DLPATH/nerdtree
  git pull
else
  git clone git://github.com/scrooloose/nerdtree.git $DLPATH/nerdtree
fi

echo

if [ -d $DLPATH/nyancat ]; then
  print -P "%B%F{green}Checking for NyanCat updates.%f%b"
  cd $DLPATH/nyancat
  git pull
else
  git clone git://github.com/koron/nyancat-vim.git $DLPATH/nyancat
fi

echo

if [ -d $DLPATH/surround ]; then
  print -P "%B%F{green}Checking for Surround updates.%f%b"
  cd $DLPATH/surround
  git pull
else
  git clone git://github.com/tpope/vim-surround.git $DLPATH/surround
fi

echo

if [ -d $DLPATH/viminesweeper ]; then
  print -P "%B%F{green}Checking for Viminesweeper updates.%f%b"
  cd $DLPATH/viminesweeper
  git pull
else
  git clone git://github.com/mfumi/viminesweeper.git $DLPATH/viminesweeper
fi

echo

if [ -d $DLPATH/webapi ]; then
  print -P "%B%F{green}Checking for WebAPI updates.%f%b"
  cd $DLPATH/webapi
  git pull
else
  git clone git://github.com/mattn/webapi-vim.git $DLPATH/webapi
fi

date > $DLPATH/latest_update.txt

