#!/usr/bin/env zsh

# Written by Göran Gustafsson <gustafsson.g@gmail.com>.

# Description: This script automatically downloads several web programming
# related git repositories i want to keep up-to-date.

# Usage: webf

DLPATH=~/Sites/Frameworks

rm -rf ~/Sites/Frameworks\ Backups
cp -R $DLPATH ~/Sites/Frameworks\ Backups

if [ -d $DLPATH/Bootstrap ]; then
  print -P "%B%F{green}Checking for Bootstrap updates.%f%b"
  cd $DLPATH/Bootstrap
  git pull
else
  git clone git://github.com/twitter/bootstrap.git $DLPATH/Bootstrap
fi

echo

if [ -d $DLPATH/Chosen ]; then
  print -P "%B%F{green}Checking for Chosen updates.%f%b"
  cd $DLPATH/Chosen
  git pull
else
  git clone git://github.com/harvesthq/chosen.git $DLPATH/Chosen
fi

echo

if [ -d $DLPATH/Deck.js ]; then
  print -P "%B%F{green}Checking for Deck.js updates.%f%b"
  cd $DLPATH/Deck.js
  git pull
else
  git clone git://github.com/imakewebthings/deck.js.git $DLPATH/Deck.js
fi

echo

if [ -d $DLPATH/Impress.js ]; then
  print -P "%B%F{green}Checking for Impress.js updates.%f%b"
  cd $DLPATH/Impress.js
  git pull
else
  git clone git://github.com/bartaz/impress.js.git $DLPATH/Impress.js
fi

echo

if [ -d $DLPATH/jQuery\ RSS ]; then
  print -P "%B%F{green}Checking for jQuery RSS updates.%f%b"
  cd $DLPATH/jQuery\ RSS
  git pull
else
  git clone git://github.com/sdepold/jquery-rss.git $DLPATH/jQuery\ RSS
fi

[ ! -d $DLPATH/jQuery ] && mkdir $DLPATH/jQuery
if [[ $OSTYPE == darwin* ]]; then
  open http://jquery.com/download
else
  links http://jquery.com/download
fi

date > $DLPATH/latest_update.txt
